### ISSUE TITLE
docker hub latest referring to v2.5.2

### ISSUE THREAD

**Issue by Shimakuchi** [shlinkio/shlink#1041]
I am using both the server and the client with the "latest" tag. Why is the server "latest" revering to 2.5.2? The Client on the other hand shows in this constellation the message.
![image](https://user-images.githubusercontent.com/2376419/109475523-1c08cb00-7a76-11eb-879f-25a60e58ec52.png)
That is why I am curious if the server "latest " should also point to the 2.6+.

Extract form [shlinkio/shlink:latest Dockerfile](https://hub.docker.com/layers/shlinkio/shlink/latest/images/sha256-e2d5ea69445de90b4275e05cfece245e3f95dfdc5b7451d4cbf7333fea90d8d3?context=explore)
![image](https://user-images.githubusercontent.com/2376419/109476161-de587200-7a76-11eb-86d6-afdd0145581e.png)

---

![image](https://user-images.githubusercontent.com/2376419/109475223-ba486100-7a75-11eb-9142-f35f2f850769.png) ![image](https://user-images.githubusercontent.com/2376419/109475271-c8967d00-7a75-11eb-93fd-4d929b36f7c7.png) -> ![image](https://user-images.githubusercontent.com/2376419/109475188-af8dcc00-7a75-11eb-8c2c-e1e1c2e3bf5d.png)

---

The "stable" tag however do have some variation in ENV and ARG  versions? I have no clue how docker files and/or your software is working but that's just what i noticed
![image](https://user-images.githubusercontent.com/2376419/109477096-ee248600-7a77-11eb-9118-affa0acb88f1.png)

**Comment by acelaya** [comment]
The issue is actually caused by the fact that the version is not passed to the image when building "latest", which makes it fall back to a default value which is hardcoded in the Dockerfile, and I update from time to time.

https://github.com/shlinkio/shlink/blob/develop/docker/build#L21

It should be passing the value "latest" as version. It's easy to fix.

That said, I would surely recommend you don't use the tag "latest" for any of the images, but "stable" instead.
