### ISSUE TITLE
Trouble Updating 2.4.2 to 2.6.2

### ISSUE THREAD

**Issue by russkiimike** [shlinkio/shlink#1056]
#### How Shlink is set-up

* Shlink Version: 2.4.2
* PHP Version: 7.4.3
* How do you serve Shlink: Self-hosted swoole
* Database engine used: MySQL

#### Summary

Having trouble updating from 2.4.2 to 2.6.2  Followed the update documentation: 

- Rename old folder version to "shlink-old"
- Unpacked 2.6.2 swoole dist to new folder "shlink". 
- Ran /bin/update, provided the shlink-old path and it started an installation questionnaire. (Don't know how update should look like) and restarted. 

Result is that the web app can't connect to the server. If I revert to the old shlink version/folder it works.

**Comment by russkiimike** [comment]
I figured it out,  so I had an extra folder which cause the daemon scrip to point to the wrong thing. However:

- I remembered last time I had a similiar issue I pointed my daemon script to `"vendor/bin/mezzio"` but should have pointed to `"vendor/mezzio/mezzio-swoole/bin/mezzio-swoole"` . What's the difference?
- In your swoole guide it said `Notice that prior to v2.5, the SCRIPT was vendor/bin/mezzio-swoole start. This will continue working but is considered deprecated and will be removed in Shlink v3.0.0. Replace it with vendor/bin/laminas mezzio:swoole:start as soon as possible`
- The 2.6.2 doesn't work with the the `"vendor/mezzio/mezzio-swoole/bin/mezzio-swoole"` because there are no executables.
- So I pointed it at `vendor/bin/laminas mezzio:swoole:start `  which I swapped for `shlink/vendor/laminas/laminas-cli/bin/laminas\` again what's the difference ?
- Also I had to apply permissions to the shrink folder but I don't know which are correct (worked with chown 777)

**Comment by acelaya** [comment]
Hello @russkiimike 

So, basically everything inside the vendor/bin folder are binaries exposed by dependencies that composer (the PHP dependency manager) symlinks there.

For example, `vendor/bin/mezzio` used to be a symlink to `vendor/mezzio/mezzio-swoole/bin/mezzio-swoole`.

In Shlink 2.5 I updated to a new major version of mezzio-swoole, which is the library used to integrate with swoole.

This major version changes the approach to execute the app, removing the script above.

Since that script was part of the recommended approach to run Shlink with swoole, it's removal was a breaking change, so I included a replacement to keep things working, but I only covered the symlink, as that was the documented one, but not the file it used to symlink.

And this takes me to the second point, as, if I understand it correctly, it has never worked for you with the symlinks inside vendor/bin folder, but you always have had to point to the original script instead (either mezzio-swoole prior to v2.5, or laminas one afterwards).

Maybe there's some issue while zipping/unzipping the symlinks. I will take a look at that.

**Comment by acelaya** [comment]
Hey @russkiimike, just a question. What operating system are you using?

**Comment by russkiimike** [comment]
Sorry haven't replied quicker, I tried to run swoole frome /vendor/bin/laminas mezzio:swoole:start and it just threw up the help output in the log... so i don't know

I am on ubuntu 20.04.1 LTS droplet DO

**Comment by acelaya** [comment]
I have been trying to reproduce the second issue, but haven't been able.

For me, o0n ubuntu 20.04, after unzipping the dist file, if I try to run any of the scripts inside `vendor/bin`, they all keep working as expected.

Can you try, for example, `./vendor/bin/shlink-install` and tell me what you see?

**Comment by russkiimike** [comment]
> I have been trying to reproduce the second issue, but haven't been able.
> 
> For me, on ubuntu 20.04, after unzipping the dist file, if I try to run any of the scripts inside `vendor/bin`, they all keep working as expected.
> 
> Can you try, for example, `./vendor/bin/shlink-install` and tell me what you see?
> 
> You should see someting like this:
> 
> ![image](https://user-images.githubusercontent.com/2719332/120102090-b4801b80-c149-11eb-8a00-e735dd0f54b8.png)

Apologies for not replying in a timely fashion.  I just updated to 2.8  and it seems like `vendor/bin/laminas` works :)
Overall I had trouble figuring out why shlink didn't work at first but then I realised that after I upgraded php 7.4-8.0, you have to reinstall swoole. Is there a better upgrade process? Anyway thank you so much !!!
