### ISSUE TITLE
Recommended CPU & RAM requirements for Docker setup

### ISSUE THREAD

**Issue by saikarthikp9** [shlinkio/shlink#1125]
#### How Shlink is set-up

* Shlink Version: 2.7.1
* How do you serve Shlink: Docker image
* Database engine used: PostgreSQL

#### Summary

What are the recommended/minimum requirements for the docker image in terms of CPU and RAM?
Assume default values for web and task workers count. And no mercure setup for realtime updates.

**Comment by acelaya** [comment]
Hey,

It's hard to tell. The reserved memory for the docker image is 128Mb at the moment, although I plan to increase it to 256 soon due to some issues, so at least set that.

As per the CPU, I would start with 0.5Gh per container and increase it if needed.

If you see that's not enough and can't increase it for whatever reason, try reducing the amount of workers.
