### ISSUE TITLE
Permission Denied ERROR when ENABLE_PERIODIC_VISIT_LOCATE=true

### ISSUE THREAD

**Issue by saikarthikp9** [shlinkio/shlink#1132]
#### How Shlink is set-up

* Shlink Version: 2.7.2
* How do you serve Shlink: Docker image

#### Summary

Getting following error with the latest docker image when ENABLE_PERIODIC_VISIT_LOCATE is set to true.

#### Current behavior

Logs show this: 
./docker-entrypoint.sh: line 39: can't create /etc/crontabs/root: Permission denied

#### Expected behavior

No error

#### How to reproduce

Use latest Docker image

**Comment by acelaya** [comment]
You are not using version 2.7, but `latest`, basically because that feature is not yet officially released 😅. It will be part of v2.8

The error you are getting is happening because of this https://github.com/shlinkio/shlink/pull/1108, that was merged recently.

I'll check if I can make the cron to be added to the new user, or otherwise roll that change back.

**Comment by onedr0p** [comment]
@acelaya you could use https://github.com/aptible/supercronic instead. It's even in the alpine pkg registry and can run as a user instead of root.

```
apk add --no-cache supercronic
```

then in your entrypoint

```bash
echo "Starting cron schedule using: $CRON_SCHEDULE"
echo "$CRON_SCHEDULE /cron.sh" > /tmp/crontab
supercronic -passthrough-logs /tmp/crontab
```

**Comment by acelaya** [comment]
Cool. Do you want to contribute the change?
