### ISSUE TITLE
Option to disable GeoLite2 but retain IP address tracking

### ISSUE THREAD

**Issue by gthbusrr** [shlinkio/shlink#1152]
Is it possible to still track IP address of visits, but disable GeoLite2? I don't need the location data but only the IP address.

Thank you so much.

**Comment by acelaya** [comment]
Hey.

Yes, all visits will be tracked even if you don't want to geolocate them.

**Comment by gthbusrr** [comment]
Hi @acelaya 

How do you do that? The only way I can prevent downloading geolite2 db is to disable IP tracking. Is there a workaround? Thanks.

I'm running on docker

**Comment by acelaya** [comment]
In order to answer that I need you to fill the issue template that you skipped, otherwise I don't know how are you running shlink.

**Comment by gthbusrr** [comment]
Hi @acelaya.

Sorry about that, I was creating an issue while I'm not logged in, and when I login, it didn't let me choose a template so I didn't know that's one... :( Really appreciated your help.


#### How Shlink is set-up

* Shlink Version: 2.8.0
* PHP Version: 8.0.9 (Information from Dockerfile)
* How do you serve Shlink: Docker image
* Database engine used: MariaDB

#### Summary


How can I track visitor's IP without geolocating them, i.e. Don't even attempt to download the database from GeoLite2.

Thank you so much!!!

**Comment by acelaya** [comment]
I'm afraid it's not possible to not even attempt to download the GeoLite db, because Shlink currently has a fallback license key, and if you don't provide your own, it will try to use that one.

However, it shouldn't have any side effects other than a couple of errors in your logs.

What's exactly the reason you don't want it to be downloaded?

**Comment by jakubgs** [comment]
I would like to request this as well. I disable all possible tracking on my instance and I see no reason why it should be even attempting to download the GeoLite DB? Why can't there be an option to entirely disable the dependency on GoeLite DB?

**Comment by acelaya** [comment]
@jakubgs if you have disabled all tracking, Shlink won't try to download the GeoLite2 db.

As per supporting an option to disable geolocation without disabling IP tracking, that will be achieved in Shlink 3.0.0 by not providing a GeoLite license key at all.

With Shlink 2.x it's not possible because there's a default fallback API key, which I can't remove until next major version due to backwards compatibility.

Shlink 3.0.0 will come soon, after v2.9 has been released, most probably, so it makes no sense to implement a config option now that will become useless in the next release.
