### ISSUE TITLE
Shlink not working (ERR_TOO_MANY_REDIRECTS)

### ISSUE THREAD

**Issue by BobDaGecko** [shlinkio/shlink#1185]
#### How Shlink is set-up

* Shlink Version: 2.8.1
* PHP Version: 8.0.11
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary

I am trying to get Shlink to work and have tried installing it about three times now. I have tried using docker and the dist file and it doesn't seem to work. After giving up on the official docs I tried searching for a guide and came across [this](https://greedme.com/how-to-install-shlink-url-shortener-on-ubuntu-20-04-server/) which worked to get it installed but every time I either try to access the short domain or connect to the dashboard in the web app it doesn't work.

Directly accessing the domain directly results in a ERR_TOO_MANY_REDIRECTS error. The web app just can't connect. I can't figure out what this issues is. I tried going through the Nginx logs but haven't found anything that would help. What could I have done wrong and how do I fix this?

**Comment by acelaya** [comment]
When Google chrome throws a ERR_TOO_MANY_REDIRECTS, it means there's an infinite loop of redirects, for example because URL A redirects to URL B, which in turn redirects to URL A again.

If you open the browser console, go to the network tab, and check "preserve log", then open one of the URLs where you are experiencing this, you will be able to see all the requests that the browser is making before failing, which should help figuring out what's wrong.

One possible reason for this to happen is that nginx (or any service in front of Shlink) is miss-configured to redirect from http to https, and also from https to http.

**Comment by BobDaGecko** [comment]
I am getting a ton of 301 redirects. I don't know what this should tell me but if it has something to do with my nginx config here it is: https://paste.nginx.org/aa

**Comment by acelaya** [comment]
Can you also share a URL where this is happening?

**Comment by BobDaGecko** [comment]
Yes, it's simply the root. https://cyfx.io but here is a short URL to try too: https://cyfx.io/7rHSx

**Comment by acelaya** [comment]
I see you are using cloudflare. It's most probably a miss-configuration there, because both URLs return a redirect to themeselves on cloudflare.

The requests are most probably not even reaching your server.
