### ISSUE TITLE
Updating env vars on dist files

### ISSUE THREAD

**Issue by antwonw** [shlinkio/shlink#1207]
Opening a new support issue here to keep the other issues closed.

Original issue:
> I've upgraded from 2.7 to 2.8 and enabled this for some of my domains, however, it's not redirecting.
_Originally posted by @antwonw in  https://github.com/shlinkio/shlink/issues/943#issuecomment-896285811_

Response:
> The redirects for the default domain are still handled through the old config or env vars. Unifying that was tricky, so I left it as an improvement for a future version.
> 
> As per the other domans, the only thing I can think of is that the domain info is not getting propagated to Shlink, so it cannot determine the actual domain. Do you have a reverse proxy in front of it?
_Originally posted by @acelaya in https://github.com/shlinkio/shlink/issues/943#issuecomment-896297385_

No, I am not using a reverse proxy at all. My installation is via the dist file, though.

> Currently, you can provide all config options with env vars only when using the docker image. When using other approaches, you need to use the installer tooling.
> 
> Supporting env vars for other set-ups shouldn't be hard and would be useful.
_Originally posted by @acelaya in https://github.com/shlinkio/shlink/issues/1015_

Since this has been introduced, this should be helpful and provide a solution to fix the above issue of changing the default domains redirects.

That said, I'm unsure how to change this since I am on the distribution files and not docker.

In the [documentation](https://shlink.io/documentation/environment-variables/) I see the environment variables to change: `INVALID_SHORT_URL_REDIRECT_TO`, `REGULAR_404_REDIRECT_TO`, `BASE_URL_REDIRECT_TO`

Further the doc page states: ```Shlink also supports providing configuration options via the so called "install tool" (bin/install script). This is an interactive CLI tool that generates some "hardcoded" configuration after being executed. This configuration will always take precedence over env vars, so you cannot combine the two of them.```

Though when I attempt to run the `bin/install` it's acting like I am installing a fresh instance.

What's the best method for updating these env vars when on the dist files?

Thanks for the suggestions and guidance!

**Comment by acelaya** [comment]
> Though when I attempt to run the bin/install it's acting like I am installing a fresh instance.

Yes, that's the expected behavior. If you want to update individual existing configurations, try running `bin/set-option`.

> I'm unsure how to change [env vars] since I am on the distribution files and not docker.

It depends on how you are running Shlink.

* For Apache, you can use `SetEnv` http://httpd.apache.org/docs/current/mod/mod_env.html#setenv
* For nginx, use `env` http://nginx.org/en/docs/ngx_core_module.html#env

If you are using something else, let me know, as all systems have a way to deal with env vars.

However, have in mind that it's currently not possible to combine options via installer tool and env vars.

If you are using a Shlink instance where you were already using the former, all the values from env vars will be overwritten.

This is a limitation sure to how configurations ate merged at runtime, so probably the best option for now is for you to use `bin/set-option`.

**Comment by acelaya** [comment]
Glad to hear it worked :)
