### ISSUE TITLE
CSV Import: Allow for importing (optional) hits per URL

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink#1241]
The import feature is really neat, making it easier to transition from other shorteners, needless to say. What I would really like would be an optional column in a CSV that allows to take the hits/clicks per URL with us. This way, we could at least have some basic statistics saved over from our former shortening solution ❤️.

**Comment by acelaya** [comment]
The CSV import is the only one that does not allow importing visits, as that would require a multidimensional data structure for which CSVs are not designed.

A column with a number is also not an option, because Shlink does not have a way to save a value like this.

If you are importing from a source that has an API, feel free to open a request to support importing from it, but the CSV source will not support visits.

**Comment by enoversum** [comment]
Thanks for the explanation, I'll open a new issue then for it!
