### ISSUE TITLE
SSL set up with shlink

### ISSUE THREAD

**Issue by agkrk6** [shlinkio/shlink#1338]
Shlink  set-up

* Shlink Version: shlinkio/shlink:stable latest
* PHP Version: 7.4.3 
* Docker image
* Database engine used: PostgreSQL
* Encryption : certbot latest, shlink has nginx.
#### Summary
SSL Shlink does not work

#### Current behavior

* Container with shlink running on http:8080 ( server) 
* Container with web client running on http:80 and https:443
Web shlink works if I connect http:80 web client to url:8080 server
Web shlink DOES NOT work if i connect web-client:443 to either server:8080 or server:8083 (for example, in compose 8083:443)

Shlink server environment variable IS_HTTPS_Enabled=true. It seems to only change the shortlink http or https address anyway.

#### Expected behavior

HTTPS enabled web client can connect to localhost:8080 and function as normal.

#### Side note

Issue may be in my nginx conf?

Has anyone successfully made this work and can shoot from the hip what might be my issue, besides gross incompetence?

Best regards,

**Comment by acelaya** [comment]
I think there's a couple of confusions here.

First, Shlink does not support PHP 7.4, bit since you said you are using the docker image, I guess that's just a typo. Otherwise, make sure to update to PHP 8.0 at least.

Second, you are probably misunderstanding the purpose of IS_HTTPS_ENABLED. From the docs: _Tells if Shlink is served with https or not (true or false). It's still **up to you** to actually serve it with HTTPS_ (https://shlink.io/documentation/environment-variables/)

Third, most of the browsers block connections to non-https sources when the web app was loaded with https. This is most probably the error in your case, as it seems you actually enabled https for the web client, but not really for the server (as per previous point).

**Comment by agkrk6** [comment]
Thank you, I get it now :)
