### ISSUE TITLE
duplicate link allowed to be created by different api key

### ISSUE THREAD

**Issue by kzshantonu** [shlinkio/shlink#1378]
<img width="459" alt="WindowsTerminal_GuUHMqusmz" src="https://user-images.githubusercontent.com/7745374/154542317-419ca89c-f4ce-4d10-9cd1-6203467a334a.png">

first link created by admin api key, second by author-only api key

**Comment by kzshantonu** [comment]
explicitly mentioning domain with -d does delete it successfully

**Comment by acelaya** [comment]
Stupid question, but did you create them from the command line? I assume not, because the concept of API key does not apply there, but since you seem to be doing all the other operations from CLI, just to confirm.

Also, I suspect one of them is not linked to any domain (which is what is considered the default domain), and the other one is linked to the default domain that somehow got explicitly created. That would explain the "-d" thing, but it should never happen, so I will investigate.

**Comment by kzshantonu** [comment]
From web app. Both. First one was not domain only but second one was. Is that why it happened?

**Comment by acelaya** [comment]
Didn't you say Author API key first? Is it author or domain-only?

**Comment by kzshantonu** [comment]
First one - admin key (no flags). Second one - author only flag. Both from web app

**Comment by acelaya** [comment]
I think the second one is not an author key, but a domain one, set to the default domain, which is a known limitation and will not work https://shlink.io/documentation/api-docs/api-key-roles/#considerations

**Comment by acelaya** [comment]
Refs https://github.com/shlinkio/shlink/issues/1379

**Comment by kzshantonu** [comment]
> it is a known limitation

I see. Interesting

**Comment by acelaya** [comment]
Just released Shlink 3.0.3, which will throw an error when trying to create a domain-only API key linked to default domain.
