### ISSUE TITLE
shlink is not GDPR compliant

### ISSUE THREAD

**Issue by wedi** [shlinkio/shlink#145]
Hi,
from what I learned, everyone using shlink in the EU as from May 25th will break the law because its recording of IPs (and maybe user agents?) is not compliant to the EU General Data Protection Regulation (GDPR).

I am not a lawyer but pretty much any article covering the GDPR states that storing plain IPs will be forbidden.

The simplest solution seems to be a setting that stops recording anything but a simple visit counter. A cool alternative could be an integration with Matomo (piwik) which is prepared to comply with the new law. Another alternative could be learning what's allowed and what isn't and adapt the statistics accordingly.

**Comment by acelaya** [comment]
Hi!
Thanks for the observation. I clearly need to dig into the new regulation, but a possible solution would be to resolve visit stats at the moment and then discard the IP address, instead of storing the address for later processing.

I'll think about it.
Thanks!

**Comment by marvinpoo** [comment]
any news on this?

**Comment by acelaya** [comment]
The thing is that I'm not really sure how to deal with this.

One option would be just disable the tracking, but I think it would be an important feature loose.

Another option would be to resolve the location, OS and such at runtime, to prevent storing IP addresses and user agents, but I'm still not sure if that would fulfill the GDPR or not.

Also, it would be an API breaking change too, as well as an important performance degradation.

Another problem would be the limit on the API shlink is currently using to geolocate IP addresses.

I'm trying to begin by discussing it with some GDPR expert, and then take a decision.

Sorry for the inconveniences.

**Comment by robwent** [comment]
You could go for some kind of ip anonymization.

The ip would still be stored until the visits get processed, but after processing the ip is either deleted or converted in a way that couldn't be converted back to the ip address, but would result in the same string for multiple visits from the same ip.

Ultimately, GDPR compliance is different for every install. If your privacy policy states that you store IP addresses for a certain period of time and visitors have accepted your policy then it's not an issue.
At the end of the day, the visitors ip address is stored in the server logs anyway.

Policies usually need to specify a data retention time, so a command to remove any visits older than a certain number of days would be good (but not needed if visits are anonymous). `shortcode:cleanup-visits --365` or something similar.
Would be a good idea anyway for installs that get a lot of hits to slim down the database.

**Comment by robwent** [comment]
Under GDPR, and ip address is considered personally identifyable information. Or it can at least be used in part to identify a user together with other information.

That's why you can't see them in things like Google analytiics.

They could just be deleted after processing, but if you ever wanted to know how many hits came from the same user it wouldn't be possible.
If they were scrambled but always resulted in the same string, you wouldn't be storing the ip, but you would know still how many hits came from a single user.

**Comment by acelaya** [comment]
Ok, got it. That's what I'll do then.

I needed to talk with someone with your know. Thanks a lot!

**Comment by robwent** [comment]
I just found this about how Google analytics handles it: https://support.google.com/analytics/answer/2763052?hl=en
They just seem to remove the final part of the ip.

I built a very basic redirection app a long time ago which didn't collect any stats itself but sent the data to Google analytics to view the stats there instead.
That could be an alternative option if people really didn't want to store that on their server..

I just had a look at the code and this was basically it:

        if ($analytics_id = Yii::$app->params['settings']['analytics']) {
      // unique identifier from the users ip address
      //The docs say that the CID “must not itself be PII (personally identifiable information)” but should take the form of a UUID
      $identifier = crc32($_SERVER['REMOTE_ADDR']);
      $fields = array(
        "v" => "1", //Version
        "tid" => $analytics_id, //Tracking ID
        "t" => "event", //Event Hit Type
        "ec" => "redirection", //Event category
        "ea" => $full_url, //Event action
        "cid" => $identifier, // Client ID/UUID
      );
      $fieldsString = http_build_query($fields);
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_URL, "https://www.google-analytics.com/collect");
      curl_setopt($ch, CURLOPT_POST, count($fields));
      curl_setopt($ch, CURLOPT_POSTFIELDS, $fieldsString);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_exec($ch);
      curl_close($ch);
    }

**Comment by robwent** [comment]
Piwik/matomo is probably also a good resourse since their software works in a similar way: https://matomo.org/docs/privacy/

**Comment by acelaya** [comment]
@robwent the feature is almost complete using Google Analytics/Matomo approaches, which, as I have seen, basically consists on obfuscating the last octet and replace it by a `0`. That doesn't affect to the IP geolocation while no longer represents the actual IP address.

However, while at first I was going to also save a one way hash of the actual address in order to be able to check visits from the same visitor, I then realized that, in combination with the obfuscated IP, you could easily figure out the actual IP. You just need to try the 256 possible combinations until you get the hash itself.

I also considered dropping the obfuscated IP once located, but there's a time span in which you can find the address, and therefore, I don't think it fulfills the GDPR.

For this reason, this feature will not be possible by now. By the moment I will just focus on fulfilling the GDPR.

---

@wedi and @marvinpoo, the implementation is almost ready and will be part of v1.12 which will be released in the next days.

Sorry for the delay and thanks for your patience.

**Comment by robwent** [comment]
Sounds good.

If you can get the location without the last octet then I would leave it like that.

**Comment by acelaya** [comment]
@robwent v1.12 is released. You can download it now https://github.com/shlinkio/shlink/releases/tag/v1.12.0

The next version on the web client will be released soon including support for deleting URLs.

**Comment by marvinpoo** [comment]
thank you so much!
