### ISSUE TITLE
domain specific basepath

### ISSUE THREAD

**Issue by hojerst** [shlinkio/shlink#1453]
#### Summary

It would be great if shlink could provide a way to configure a basepath according to a domain. Currently the $BASE_PATH is taken into account for each domain, however I really like to use the following layouts at the same time:
1. `longerdomain.com/basepath/key`
2. `shrt.com/key`

My suggestion would be to create either a rest endpoint for this as it is done for the domain specific redirects or just have global config via env for that (e.g. an env var `BASE_PATH_domainpart` where `domainpart` would be a transformed domain name - e.g. `my-domain.com` `MY__DOMAIN_COM`)

**Comment by acelaya** [comment]
The problem with this is that the base path affects a couple of startup-time configurations, where the requested domain is not yet known.

It would also introduce a lot of complexity, for something usually unlikely to be needed. If you are serving multiple domains under the same instance, it's because you want the configuration to be shared. Having different base paths would also make things unnecessarily complex at the reverse proxy side.

I would recommend using different Shlink instances if you need different configurations for every domain.
