### ISSUE TITLE
API: Allow for adding multiple domains to a new API key, disallow new domains

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink#1454]
As far as I understood, generating a restricted API key only lets me limit it to one specific domain and not multiple. It's not urgent, but it would be nice to be able to provide multiple domains that the user can use and see stats for. 
Also, even if the new API user has no access to server settings and such, it seems one could still (pseudo-)add new domains in the web UI. Is it possible to remove that for restricted API keys?

**Comment by acelaya** [comment]
The "API key roles" is a feature that introduced a lot of complexity and edge cases. I implemented it because it was sponsored, but I don't know if it was the best idea, and I don't wish to extend it any further.

Also, this has more considerations than it seems. For example, created short URLs with an API key having the DOMAIN_SPECIFIC role, will always be linked to that domain, ignoring any provided one. If the role was linked to multiple domains, there's no way to know which one to implicitly set.

**Comment by enoversum** [comment]
Hi @acelaya , thanks for your explanation, I understand you won't expand on this feature. I had no idea about the technical implications. In fact, I was just hoping for a way to create a user that can only see, create and alter short URLs for some or one domain. Maybe there'll be a different way to handle this in the future you'll come up with, but on any account, thanks for your hard work on Shlink so far 😊!
