### ISSUE TITLE
Allow for authentication via GET Parameters

### ISSUE THREAD

**Issue by proffalken** [shlinkio/shlink#146]
A number of social media management tools assume that the link shortening software used will accept authentication tokens as part of a GET request rather than a POST, for example Mautic (www.mautic.org) has the following text when you try to add a new Link Shortening solution:

```The full URL (including access key) to your url shortener that, when queried, returns a plain text shortened url. For bit.ly users, use `https://api-ssl.bitly.com/v3/shorten?access_token=[ACCESS_TOKEN]&format=txt&longUrl=`, replacing [ACCESS_TOKEN] with your bit.ly access token.```

At present, as far as I can tell, it is only possible to authenticate using a POST request.

**NOTE:** I am *not* requesting that the key rotation is removed, this makes sense to me from a security POV and I will work out a way to update this in Mautic on a weekly basis as required.

**Comment by acelaya** [comment]
I see your point and it looks like an interesting feature. It shouldn't be hard to implement, so I'll probably do it.

Thanks for the request.

I just have one question. Do you know if mautic properly sends the "Accept" header requesting text/plain on the request? If so, I would probably use it in order to decide if the response should be plain text or JSON. Otherwise, maybe a query parameter should be used.

**Comment by acelaya** [comment]
By the way. If this was implemented, I wouldn't make the endpoint expect a JWT, but the API key itself. It makes more sense when integrating with third party services on which you have no control.

**Comment by proffalken** [comment]
Firstly, thanks for such a quick response!

I've logged a bug (https://github.com/mautic/mautic/issues/6023) on the Mautic side of things to see if they can deal with this as well - I've requested that they add the headers as a "short-term solution" assuming that they don't already.

**Comment by acelaya** [comment]
The feature has been implemented and will be present in the upcoming v1.9.0

In the case of mautic you will have to provide something like `https://your-domain.com/rest/v1/short-codes/shorten?apiKey=[YOUR_API_KEY]&format=txt&longUrl=`. This will return the short URL in plain text.

If the `format` parameter is not provided, the response will be a JSON object with the same structure as the one for the regular short URL generation endpoint.

The system takes into account both the `Accept` header and the `format` query parameter, so that you don't have to depend on the third party service implementation.

**Comment by acelaya** [comment]
I have just released Shlink 1.9, which includes the new feature. https://github.com/shlinkio/shlink/releases/tag/v1.9.0

I'm now preparing an update on the website to document this feature.

Thanks for using shlink!

**Comment by proffalken** [comment]
Amazing, thank you so much!

**Comment by proffalken** [comment]
Oh, @acelaya - is there a documented upgrade process anywhere? The installation process seems to suggest that I should start from scratch again, and the content of the zip file is very different to the existing layout on disk that I have for 1.8.1

**Comment by acelaya** [comment]
You have to use the bin/update script, which will allow you to import the
configuration from a previous installation.

--
Alejandro Celaya Alastrué
https://www.alejandrocelaya.com
