### ISSUE TITLE
Support additional request methods on short URLs

### ISSUE THREAD

**Issue by KashifSaadat** [shlinkio/shlink#1653]
#### Summary

Currently it seems only the GET method is supported when accessing a generated short URL. When attempting other requests such as PUT or POST, a 302 redirect occurs based on the `DEFAULT_REGULAR_404_REDIRECT` setting.

It would be great to have support for any request methods to be forwarded on as-is to the long URL.

**Comment by acelaya** [comment]
Can you elaborate on what context do you expect a request other than GET to a short URL?

**Comment by KashifSaadat** [comment]
Hi @acelaya, as an example I have shortened url and I am performing a PUT request to upload a file to it.

**Comment by acelaya** [comment]
I see.

I'm afraid that wouldn't work as you think, even if Shlink allowed other methods.

The way standard HTTP redirects (301/302) work, is that basically the server is telling the client to perform a new GET request to a new URL.

Only some params are kept, like some headers, but not the original method or body, so the long URL would not necessarily get a PUT request with the uploaded file.

However, using 308 and 307 redirects, it could be that this can be achieved, but I need to investigate and test it, as such change would impact how Shlink is currently configured, potentially introducing a regression.

**Comment by acelaya** [comment]
See:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307

**Comment by KashifSaadat** [comment]
Thanks for the response 👍  So from the above docs a 307 or 308 redirect should hopefully be correct for this type of use case. To avoid potential regressions could a check be performed on the request type, so when it's anything other than GET or HEAD a 307 response is sent instead to preserve the original request body and method?

**Comment by acelaya** [comment]
Yeah, that would be an option.

The only thing is that currently users can configure if they want Shlink to send 301 or 302 redirects. The first thing that comes to mind is to use 307 for non-GET non-HEAD requests for anyone who configured 302, and 308 for those who configured 301, as they are supposedly equivalent, but there are some considerations:

* The spec mentions 307/308 exist since 2014, meaning some software might not know how to handle them.
* I can see some users complaining about Shlink using a status code different than what they explicitly configured, even if it's supposedly equivalent, so this should be somehow informed and documented.
* Shlink cannot start redirecting on non-GET requests, as that would be a breaking change, and therefore, it needs a separated feature flag, which also depends on previous point.
* I also need to check how cache behaves with 307/308, as it's currently also configurable.
* Everything stated there is mostly "thory", and it needs to be tested in different scenarios.

One option would be to allow users to select between 301, 302, 308 and 307 redirects, explaining that the last two will implicitly allow redirects for methods other than GET, and warning that their usage is risky if very old software gets involved.

**Comment by KashifSaadat** [comment]
`I can see some users complaining about Shlink using a status code different than what they explicitly configured, even if it's supposedly equivalent, so this should be somehow informed and documented.` - especially if they have any checks performed on the redirection type.

Perhaps the safest option would be a feature flag, or as you mentioned in your last point, allowing users to select 307/308 redirects with accompanying information on the change in behaviour.

**Comment by acelaya** [comment]
I have just createdthe PR to add support to this.

In the ADR you can see all considered options, and the one finally chosen https://github.com/shlinkio/shlink/pull/1657/files#diff-c322042c5a77be45e3d7662bf82e46d430e417b8edf320ff6b99e17405d0840e

**Comment by KashifSaadat** [comment]
Thank you for adding support for this so quickly! 🙇
