### ISSUE TITLE
Purge all orphan visits

### ISSUE THREAD

**Issue by viktorix** [shlinkio/shlink#1681]
#### Summary
This could be a question if it's already possible. I couldn't find anything. It would be nice if there was an option to purge/delete all orphan visits. Maybe something like: `visit:purge-orphan`.

For now, I was able to delete them using SQL command and checking for the 3 link types.

**Comment by acelaya** [comment]
Do you want to be able to delete them because you actually don't want to track orphan visits, or is it that you want them, but periodically want to start from scratch?

If it's the first, you can actually opt-out entirely to orphan visits tracking. It was discussed here recently https://github.com/shlinkio/shlink/discussions/1671, and it's also documented at the end of this section https://shlink.io/documentation/tracking-visits/#orphan-visits

If it's the second, can you elaborate on the use case?

**Comment by viktorix** [comment]
The second one. I do want to keep tracking them, but there's no reason to have thousands of them from the beginning of time increasing db size. 99% of them are bots and hackers scanning for vulnerabilities. 

Maybe even a setting to keep X days worth of orphan logs would be good.

Once I review the logs from time to time, I purge them (SQL command).

**Comment by acelaya** [comment]
Got it.

It's something tricky. I have been deliberately avoiding such a feature, because a bug on it could have really bad consequences. Worst case scenario, you end up with all visits whipped out.

That said, it's not something really hard to implement, and it has been requested in the past (see https://github.com/shlinkio/shlink/issues/1222 and https://github.com/shlinkio/shlink/issues/1110).

I guess it would be ok if I cover it carefully with a bunch of tests.
