### ISSUE TITLE
Docker - Service could not be created - Address in use

### ISSUE THREAD

**Issue by tomy137** [shlinkio/shlink#1743]
#### How Shlink is set up

Just by this command : `docker run -e DEFAULT_DOMAIN=s.test shlinkio/shlink:stable`

#### Summary

When I run this command, the Docker can't short my link : 

```
In ServiceManager.php line 627:
Service with name "Swoole\Http\Server" could not be created. Reason: failed to listen server port[0.0.0.0:8080], Error: Address in use[98]
In HttpServerFactory.php line 117:
failed to listen server port[0.0.0.0:8080], Error: Address in use[98]
```

I've just followed the "[Install using a docker image](https://shlink.io/documentation/install-docker-image/#install-using-a-docker-image)" documentation.

Seems to be OK with the roadrunner version. No error. 

**So my questions are : why is it not working with openswoole ?** Maybe Docker version as to be choose with roadrunner by default ? Do I need to know differences between the two "flavor" ? I can't manage to find anything in the documentation to help me. Is there something I've missed ?

Thanks in advance for your help.

**Comment by acelaya** [comment]
You are not doing anything wrong. This is actually a bug.

**Comment by acelaya** [comment]
I would recommend sticking with the roadrunner version though, as there have been other reports on low-level issues which happen with openswoole only, and soon roadrunner will become the default runtime.

**Comment by tomy137** [comment]
Ok great ! Thanks for your reactivity !

**Comment by acelaya** [comment]
I realized this has been happening for some time, so I guess people using openswoole do not usually create short URLs from the command line.

The reason is that creating a short URL triggers an event to notify a real-time update, which requires using roadrunner jobs or openswoole tasks.

The former only works when done inside an openswoole request, so it sadly needs to be disabled and documented.

Using roadrunner everything should work as expected, and updates should be notified no matter what.
