### ISSUE TITLE
Mark as Bot or Block IP

### ISSUE THREAD

**Issue by DunklerPhoenix** [shlinkio/shlink#1747]
Edit: i rushed the first issue a bit. So here is a better version:

Heho
I have many orphan visits from bots which not counted as bots that try to find wordpress plugins or other stuff for finding security issues etc.

It would be great to have a set of features to:
- Block requests or marl as bot from special orphan addresses
e.g if /wordpress/plugins/ is called I can set this to a list and shlink will mark it as bot or block any request to a orphan address that contains this value (regex or wildcard list)
- mark IPs manually as Bots
- blocklist for IPs

**Comment by acelaya** [comment]
Anything related with "blocking" is out of Shlink's scope, and there are better tools that you can put in front of Shlink to block bot traffic.

As per improving bot detection, I might consider it, as right now it's based on the user agent (that's why the chosen wording is "potential" bot, and not just bot, as there's no way to guarantee 100%).

**Comment by acelaya** [comment]
Closing, due to lack of capacity and other priorities.
