### ISSUE TITLE
API Key only for creating, not for viewing or editing or deleting short urls

### ISSUE THREAD

**Issue by XNonymous-N2** [shlinkio/shlink#1762]
#### Summary

Hey!

I just wanted to ask if there is a way to create an API key just for creating short urls.
All other features should not be executable by this API key.

When I use PrivateBin in combination with Shlink, I have the problem that my API key gets exposed.
So the best would be, that the user can do nothing special with this key.

Best regards!

**Comment by acelaya** [comment]
Could you elaborate on how PrivateBin and Shlink interact here? Because you should not be exposing API keys at all, that's quite concerning on its own.

**Comment by XNonymous-N2** [comment]
Its quite similar with #1106

**Comment by acelaya** [comment]
Yes, but what's the point. What are you trying to achieve, and in what context do you need to expose the API keys.

**Comment by XNonymous-N2** [comment]
I know its not intelligent to expose API keys at all. But PrivateBin only let me do it like this.
So my mission was that, a user can see the API key, but can't get information with it, only create shorted urls with it.. 
(not good at all but better than also see all other links)

**Comment by acelaya** [comment]
But what are you trying to achieve. I still don't get how PrivateBin and Shlink need to interact here.

If you can explain the actual use case, maybe I can suggest a better approach.

The API key permissions system is not going to be evolved in a direction where only write operations are allowed, so that's not an option.

**Comment by XNonymous-N2** [comment]
When you create a paste in PrivateBin it is a long link, and I want to short it.
And as in #1106 explained, PrivateBin lets this only happen (afaik) on the user site, so the API Key gets exposed everytime.

From my site, the solution from PrivateBin is not good, but I don't know what I should to do prevent first, that the API Key gets exposed and second, that when you have it, you can't get access to all data which was generated from this key

**Comment by acelaya** [comment]
Ah, I think I'm starting to get it.

So PrivateBin lets you somehow integrate with a URL shortener of your choice, in order to generate short urls to posted content, correct?

And apparently, they do this integration on the client side, which exposed any kind of credential required for that integration (in the case of Shlink, the API key).

If these assumptions are correct, then this looks like an incorrect design on PrivateBin side, and something that should be addressed there.

Addressing it on Shlink as you suggest, is just a workaround that does not really protect you completely. It would introduce more complexity, a feature which won't be very useful in most of the cases, and the false impression of security.

So I would suggest opening an issue or discussion on PrivateBin repository to see if this can be changed there.

**Comment by XNonymous-N2** [comment]
Yes! Exactly so it is. I'm sorry for opening a issue here :)
Have a good day!

**Comment by acelaya** [comment]
Welcome!
