### ISSUE TITLE
More options to customize automatically generated short codes 

### ISSUE THREAD

**Issue by hamidabbaszadeh** [shlinkio/shlink#1856]
#### Custom regex for slugs

In addition to "Strict" and "Loose" mode for slug generation, it's good to add custom regex, so one can define what kind of slugs that want to be used.

**Comment by acelaya** [comment]
Can you explain your use case?

**Comment by hamidabbaszadeh** [comment]
Maybe I didn't get my point across. I mean that, it good to have a option for choosing Letters or Numbers.

Some time, we want to have slug only with Letters and sometimes only with numbers.

So, I though that maybe it is possible to use regex for generate slugs.

for example:  
I want to generate slugs with this regex `/[a-z]{2}[1-9]{2}/` two letters followed by to numbers (without Zero).

**Comment by acelaya** [comment]
Yeah, the technical part of the request was clear. My question is more why do you want to do that.

**Comment by acelaya** [comment]
But custom slugs are provided by you. Just provide whatever value you think it's nice 🙂 

The [short URL mode](https://shlink.io/documentation/some-features/#short-urls-mode) is intended to slightly change the logic to resolve already created short URLs at runtime. If you create `https://s.test/my-cool-campaign`, with `strict` mode, visitors to `https://s.test/MY-COOL-CAMPAIGN` would get a 404, while on `loose` mode, it would still redirect.

Also, when `loose` mode is enabled, short codes generated by Shlink will never have uppercase letters.

If your problem here is that you don't trust yourself or others when it comes to provide custom slugs, and want to validate they match a specific RegExp, then this falls on a different "bucket", not related with the URL mode.

If you are actually talking about providing a RegExp so that all short codes generated by Shlink match that, that was kind-of possible long time ago (you could provide the alphabet from which Shlink picked the chars for new short codes) but it was a source of lots of problems, so it was removed.

Automatically generating short codes based on a RegExp would be even more challenging, as it has a lot of implications. For example, your example more or less has an implicit size, but that doesn't need to be the case.

**Comment by hamidabbaszadeh** [comment]
Please forget 'regex' and what I said.

Functionallty of 'Strict' and 'Loose' modes  are clear.

Slugs are generated using the following pan function:

```
‍‍function generateRandomShortCode(int $length, ShortUrlMode $mode = ShortUrlMode::STRICT): string
{
    static $shortIdFactory;
    if ($shortIdFactory === null) {
        $shortIdFactory = new ShortIdFactory();
    }

    $alphabet = $mode === ShortUrlMode::STRICT
        ? '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
        : '0123456789abcdefghijklmnopqrstuvwxyz';
    return $shortIdFactory->generate($length, $alphabet)->serialize();
}
```

There are two options. How about to add more options?

**only letters**: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
**only lower case letters**: 'abcdefghijklmnopqrstuvwxyz'
**only numbers**: '0123456789'

**Comment by acelaya** [comment]
The short URL mode is not meant to define the shape of generated short codes, but how short URLs of any kind are resolved at runtime.

Yes, there's a side effect which is that, for loose mode, it simplifies things if generated short codes never have uppercase letters, but there are other places where the mode is checked and behavior is different. How is it supposed to behave for these new modes?

Also, what if you want only numbers on generated short codes and still custom slugs be case-insensitive?

So, for me it's clear this is a separated feature from short URL modes. Basically you want to be able to customize the alphabet for generated short codes, which was possible in the past, and is very problematic because people miss-use it.

For example, the alphabet affects the entropy/randomness of short codes, and the chance for conflicts. With an alphabet of '0123456789' you can quickly run in short code collisions unless generated short codes are long enough, which defeats the purpose of having short URLs.

With that in mind, if the only reason for this request is that currently you feel generated URLs are "ugly", I'm afraid I have to say no.

It's a very niche use case for the added complexity and overhead dealing with future opened issues for a miss-use of the feature.

Usually, when using URL shorteners, you don't care about how the URLs look, as long as they are short. If the look is important, then you provide a custom slug.
