### ISSUE TITLE
Allow filtering by tag on visits page

### ISSUE THREAD

**Issue by samtuke** [shlinkio/shlink#1922]
### Summary

The existing Visitors chart with time series filtering, and CSV export, are very powerful. But they only support few use cases currently, and do not provide access to much of the available data in the database. 

Specifically I'd like to be able use the graph and export functionality for viewing and exporting specific types of visitors. The first case for this would be to support filtering by tag, using the existing filters dropdown menu.

This would allow restricting the visits shown on the Visitors page to visits associated with URLs with a specific tag.

### Use case

1. As a sales manager at a small business
2. I want to track the sources of visitors to my sales call booking page
3. And I want to use Shlink tags to achieve this
4. So that when I go to the Visitors page in Shlink
5. I can see only link visits to a given URL
6. Which used a particular tag
7. Where the tag represents the source of the visitor (e.g. email or website)
8. So that I can see how many visitors came from a given source (tag) in a specified timeframe
9. So that I can manually compare the number of visitors with one tag, vs another
10. And when I change the timeframe
11. The visitors chart is updated automatically, as before
12. And when the export button is pressed
13. The downloaded CSV reflects the tags filter which has been applied

Related potential future feature functionality:

1. Compare visits with different tags visually by showing multiple chart lines at the same time
2. Compare visits with the previous time period visually (like in Google Analytics, Matomo, etc.)

**Comment by acelaya** [comment]
There's a couple of different topics here. First the easy part.

> * Compare visits with different tags visually by showing multiple chart lines at the same time
> * Compare visits with the previous time period visually (like in Google Analytics, Matomo, etc.)

This has been on my radar for some time. See https://github.com/shlinkio/shlink-web-component/issues/7 and https://github.com/shlinkio/shlink-web-component/issues/9

I don't want to bet my life on it, but the intention is to have it done for next shlink-web-client release.

> I'd like to be able use the graph and export functionality for viewing and exporting specific types of visitors. The first case for this would be to support filtering by tag, using the existing filters dropdown menu.
> 
> This would allow restricting the visits shown on the Visitors page to visits associated with URLs with a specific tag.

Regarding to this, I think you may not be understanding how tags work in Shlink.

Filtering by tag when you are displaying visits for a particular short URL would not make any difference.

If a short URL has received 100 visits, they have happened for the short URL as a whole. When a visit occurs, there's no notion of the tag at all, so Shlink does not track tags on the visit itself.

In Shlink, tags are used to "group" related short URLs, so that you can see how all of them behave together. In fact you can already load all visits for a specific tag, which will get you the visits combined for all short URLs which have this tag.

> ### Use case
> 1. As a sales manager at a small business
> 2. I want to track the sources of visitors to my sales call booking page
> 3. And I want to use Shlink tags to achieve this
> 4. So that when I go to the Visitors page in Shlink
> 5. I can see only link visits to a given URL
> 6. Which used a particular tag
> 7. Where the tag represents the source of the visitor (e.g. email or website)
> 8. So that I can see how many visitors came from a given source (tag) in a specified timeframe
> 9. So that I can manually compare the number of visitors with one tag, vs another
> 10. And when I change the timeframe
> 11. The visitors chart is updated automatically, as before
> 12. And when the export button is pressed
> 13. The downloaded CSV reflects the tags filter which has been applied

(Unrelated, but this is more a "user story" than a "use case". A user story explains "how", while a use case explains "why")

What you are describing here sounds like A/B testing. You basically want to check how two things are performing compared to each other.

In a service like Shlink, A/B testing can be done in two ways:

* By having two different short URLs redirecting to the same place, which are distributed in different channels, and then you want to see which had more visits (this can already be done).
* By having a single short URL which dynamically redirects to different places, and then you want to see which has better "performance" (this is not possible at the moment. See [this RFC](https://github.com/shlinkio/shlink/discussions/1912)). 

There have been similar requests in the past. These are some related issues: https://github.com/shlinkio/shlink/issues/1898, https://github.com/shlinkio/shlink/issues/366, https://github.com/shlinkio/shlink/issues/1902

But, as mentioned above, I don't see how tags would help here.
