### ISSUE TITLE
Set cache lifetime per short url

### ISSUE THREAD

**Issue by nwalke** [shlinkio/shlink#2091]
### Summary

I know that cache lifetime and ability to set cache status code was previously added.  It looks like there was some discussion about allowing it at the short url level, but that never got added (or I'm too dumb to find it).

I think this has two parts:

- Set cache lifetime per short url
- Set return status code per short url

### Use case

Setting a cache lifetime at the instance level is great and all, but what if I have a short url I never change and would like to simply redirect forever?

Or the opposite, I have a short url that I change all the time.  Right now it would be impossible to get the settings right out of one instance of shlink.

**Comment by acelaya** [comment]
You are correct. Adding settings per short URL was discussed, but never implemented, as global settings are enough in most of the cases. 

It would be possible to add this setting now, but first you need to understand the exact purpose of this cache, how redirect statuses work, and the context of why things were implemented this way.

When this feature was implemented, Shlink only supported redirecting users via status 302. This is considered a temporary redirect which basically tells consumers "I want you to go to this other URL instead, but next time ask me again, as I may want you to go to a different one".

This is technically not correct, as in most of the cases you will always redirect to the same place. However, it seemed the only way to track visits properly, as consumers will continue hitting the server on every request. 

This technicality affects SEO, and that's why it was requested for Shlink to support 301 redirects as well. Those are considered permanent redirects, meaning "I want you to go to this other URL instead, and this will continue being true in the future forever".

In practice, this tells the browser they can cache this redirect client-side, and never hit the server again, which means, subsequent visits of the same user would not be tracked by Shlink, as the visit would never reach it.

That's where cache times start to make sense. If you return a status 301 with a specific cache time, it suddenly means "I want you to go to this other URL instead, and this will continue being true for the next 60 seconds. Then ask me again".

This means you can have proper SEO, but if the same person visits the short URL later in time, the visit will be properly tracked by Shlink. Only subsequent visits happening in those first 60 seconds will cause the browser to redirect "client-side" without hitting the server. 

And why is this cache time configurable? I checked how other similar services set this value, and didn't find consistency. Some set 30 seconds, some set 60, some set 90... So I decided to let users choose. 

Configuring infinite cache times would have two main bad side effects: 

* You would never track more than one visit per user, even if they access more times, producing incorrect stats and making you take incorrect decisions.
* If you make a mistake and realize you configured the wrong long URL, changing that would have no effect for any user who already visited the short URL, as the redirect will have been cached at the browser level, where you don't have any control. Those would continue being redirected to the wrong URL no matter what. 

With all this in mind, do you still really want to configure an infinite cache in a short URL? I don't think so 😅

And other than infinite cache times, having a short URL with a 1 min cache, other with 2 min and others with 30 seconds is a level of granularity that doesn't really add a lot of value, so it wouldn't justify the added complexity.

**Comment by acelaya** [comment]
I think there's still a misconception here, it's not a matter of project goals. 

The point when using status 301 vs status 302 is not about caching. Caching is a side requirement that only needs to be fulfilled because the spec demands it.

When you implement caching somewhere it's usually because there's a performance bottleneck that cannot be solved in a different way. This is not that. Shlink does not need caching for short urls, and it's perfectly fine if all requests hit the server.

It feels like you are trying to solve a problem you don't really have, or instead, you do have an actual problem, you tried to work around it with the tools available, you almost succeeded, and now you are actually asking for changes that would allow you to actually apply that workaround (AKA, [the XY problem](https://xyproblem.info/)).

So I have to ask, are you experiencing some performance issues with your Shlink instance, around visits to short URLs? Perhaps you have a lot of traffic and thought this would mitigate those problems. 

If that's the case, let's focus on that problem, otherwise, don't worry that much about caching requests, because most probably you don't need it, and you'll end up shooting yourself in the foot.

**Comment by acelaya** [comment]
> Just to be clear, I wasn't trying to be sarcastic or come across any other way than grateful for the project. It works splendidly and I appreciate the work you've put into it!

No worries, it didn't come-up as sarcasm to me 🙂 

> I'm using shlink behind cloudflare tunnels and would love to have the origin set a cache control header on the response so that cloudflare caches that redirect and simply returns it upon client request.
> 
> There's no "problem" per se, was just trying to see if I could accomplish the same result without cloudflare having to route back through the tunnel to get a fresh response. With the cache control header having "private", cloudflare won't cache it.

This more or less confirms my suspicion about the "XY problem".

You basically tried to see if anything on Shlink would allow you to do something, found a feature somewhat related which didn't fully cover your needs, and opened an issue to see how to tweak that somewhat-related feature to become a feasible workaround 🙂.

But since that feature has a different purpose, the whole conversation became confusing.

The "Use case" part of the issue template is precisely meant for you to describe how you (and others) would benefit from the feature you are requesting. What is the "use case" in which you plan to use it and how, but don't worry, most of the people just repeat the same they explained in the summary, but with different words 😅 

Now that I understand what you are trying to accomplish, perhaps I can think on the right way to approach it, as it indeed sounds like a legit scenario.

The scenario I extract from all this is having a single Shlink instance with a CDN service in front of it. Without proper reverse-proxy caching headers, end-users would not benefit from accessing an edge server which is close to them, as the request would always need to go to the upstream server no matter what.

Am I getting the problem right this time?

**Comment by acelaya** [comment]
I have created this issue https://github.com/shlinkio/shlink/issues/2093. Feel free to track it
