### ISSUE TITLE
Failed to import custom slug from Bitly.

### ISSUE THREAD

**Issue by TokuiNico** [shlinkio/shlink#2095]
### Shlink version

3.7.3

### PHP version

8.2.13

### How do you serve Shlink

Docker image

### Database engine

MySQL

### Database version

8.0.32

### Current behavior

I imported short links from Bitly and noticed that the short links with a custom slug (e.g., https://www.custom.com/custom_slug) were skipped, while the short links with just a custom domain were successfully imported (e.g., https://www.custom.com/random_slug).

### Expected behavior

Import all short links, whether they have custom slugs or not.

### Minimum steps to reproduce

1. Generate two Bitly short links: one with a custom domain and the other with a custom domain and slug.
2. Import short links using Shlink CLI.

**Comment by acelaya** [comment]
I can see there's a bug in the logic when reading custom slugs, because bitly seems to be still generating a random short code under the hood, and its API returns the custom slug in a different field.

However, this should not make the links to be skipped, but to be imported with that random short code instead of their custom slug (this is what I experienced while testing this).

Can you confirm what's the exact behavior you are experiencing? Did you explicitly see the "Skipped" keyword in the console for those, or did they get imported with an "unknown" random slug/short code?

**Comment by TokuiNico** [comment]
Thank you for your response. I checked the shlink database and did find short URLs using random short codes.

I expected that in this situation, shlink would use a custom slug instead of the random code generated by bitly, or provide an option for me to decide which slug to use. This way, I can fully migrate my bitly short URL service to shlink.

**Comment by acelaya** [comment]
> I expected that in this situation, shlink would use a custom slug instead of the random code generated by bitly

Yes, that's the intended behavior. I'll get that fixed.

**Comment by acelaya** [comment]
Shlink 4.1.0 has just been released, which includes this fix.

**Comment by TokuiNico** [comment]
Thanks for your help!
