### ISSUE TITLE
Can't delete a shortened url

### ISSUE THREAD

**Issue by gravelfreeman** [shlinkio/shlink#2104]
### Shlink version

4.1.0

### PHP version

unknown

### How do you serve Shlink

Docker image

### Database engine

PostgreSQL

### Database version

unknown

### Current behavior

1. Create a link through CLI or within web-client
2. Try to delete any link and get this error message flashing (had to take a screenshot)

![image](https://github.com/shlinkio/shlink/assets/44218371/3769a184-2528-47ba-8ee3-965c82b03c6d)

### Expected behavior

Enter word delete and press the delete button. Link deleted.

### Minimum steps to reproduce

I'm using the Truecharts deployment.

I checked if it could've been an option with env vars but couldn't find anything relevant but this one `DELETE_SHORT_URL_THRESHOLD` which I haven't configured. Unless it would be hidden in the Truecharts deployment.

**Comment by acelaya** [comment]
Shlink does not allow deleting short urls with more than 15 visits, to avoid losing data by mistake. 

The `DELETE_SHORT_URL_THRESHOLD` env var is precisely used to customize this threshold, allowing you to provide a different value, or disabling the check entirely by setting -1.

However, if this threshold was the cause, the error message would be different. Can you check Shlink logs? There should be an error trace when that happens.

**Comment by acelaya** [comment]
I'll move this to discussions, as it doesn't seem to be a bug, but rather a configuration issue.

> The server logs doesn't log anything when I'm trying to delete or edit

It might the the request is getting blocked before reaching Shlink then. What do you see in the browser console's network tab when trying to do any of those actions?

There should be a request failing which should be returning a response, or perhaps there's a blocked request due to CORS not working properly if the ingress or whatever host in front of Shlink is messing-up with the CORS headers. 

> The web-client is full of these lines which seems like the normal behaviour I guess.

Yeah, those seem to be liveness proves from Kubernetes.
