### ISSUE TITLE
Text note to links

### ISSUE THREAD

**Issue by morphinestyle** [shlinkio/shlink#2110]
### Summary

I would like to propose a request for a feature: the possibility of inserting notes to the created link.
**It is a feature as simple as it is important.**

It would allow you not to keep separate records and archives to add simple notes for each link.

### Use case

For example: you can track where this link has been used, so you can understand "where it will impact" if it is modified or deleted.

Or temporary links that need to track the source replacement.

**Comment by acelaya** [comment]
Why not using tags for that?

**Comment by morphinestyle** [comment]
I already use them extensively (and they work very well) to set the type of content and the company, for example:
**[company1] [technical-sheet] [pdf]** or **[company2] [web-page]**

While with the notes I could add:
- packaging4
- packaging22
- packaging18
- packaging30

or again:

- old URL link replacement, do not delete

Forcibly, tags could be used to manage this situation, but it would mean creating dozens and dozens of useless tags (used only once) which would only generate unnecessary confusion and errors.

**Comment by acelaya** [comment]
Hmm, yeah, I see.

Unfortunately, I feel like this does not belong to Shlink, or it's a too niche use case. It's so abstract and open that feels like the kind of feature which becomes "a bucket of stuff I don't know where to put, but seems convenient here" 😅 

As soon as something like this landed, people would start to see cadences, and request variations and changes on top of it, that it would become a product of its own inside Shlink.

I would personally just use a side tool to handle metadata and notes around links, perhaps just an online spreadsheet that you can share with your team and has built-in permissions and such.

I'll leave this open just in case I'm wrong and it turns out it's precisely what every short URL user needs, but if it doesn't get a lot of attention, I don't think this gets implemented any time soon.

I'm also open to see examples of other similar tools with such a feature, just in case I'm actually missing something.

**Comment by morphinestyle** [comment]
One of the services I used that highlights the presence of NOTE and the presence and type of REDIRECT

![image](https://github.com/shlinkio/shlink/assets/35969533/dc7020bb-907d-4d21-8bed-b4415af19d02)

**Comment by morphinestyle** [comment]
Here you can already see where the link is used without needing to enter the link

![image](https://github.com/shlinkio/shlink/assets/35969533/6e2fa054-af0c-4d0a-b5da-67ffc08da33b)

**Comment by acelaya** [comment]
What service is this?

**Comment by morphinestyle** [comment]
https://openmylink.io
It's a good service.

Il mar 23 apr 2024, 23:46 Alejandro Celaya ***@***.***> ha
scritto:

**Comment by acelaya** [comment]
No one else seems to be reacting to this. Closing.
