### ISSUE TITLE
Flag to disable shared slug

### ISSUE THREAD

**Issue by JasonHK** [shlinkio/shlink#2154]
### Summary

Add a flag to Shlink, when a slug was added without a domain specified, the default domain will be explicitly added (so that other domains will not redirect this slug).

### Use case

The current behaviour for Shlink is if a new slug was added with no domain specified, any domain pointed to Shlink will redirect to that long URL, unless a slug for the domain also exist. This behaviour is not ideal for a multi-domain setup.

**Comment by acelaya** [comment]
This topic was brought up some time ago here https://github.com/shlinkio/shlink/discussions/1535

You can find some context on why multi-domains work like that, and the complexities to change that behavior. 

As a result of that discussion, I created an issue https://github.com/shlinkio/shlink/issues/1536, but later on closed it due to the lack of attention.

The type of issue means that this feature is too complex to implement, and has a lot of considerations, for the benefits of brings, so I'm going to close this. 

If enough people decide to support the project, I will reconsider.
