### ISSUE TITLE
Allow "&" and "+" characters in custom slugs again.

### ISSUE THREAD

**Issue by tiritibambix** [shlinkio/shlink#2156]
### Summary

Hi there!

I'm a big fan of shlink and have been using it for over a year now. It's been a great tool for me, super efficient and convenient.

I do have a small request though - I used to be able to use characters like "&" and "+" in my custom slugs, which was really handy for readability. It would be awesome if I could use them again.

I receive this error:
```
Provided data is not valid

Invalid elements: [customSlug]
```

Thanks so much for considering this!

### Use case

/T+B-lunch
/T&C_car

**Comment by acelaya** [comment]
> I used to be able to use characters like "&" and "+" in my custom slugs

In what version did you stop being able to use those? I don't remember making a conscious decision to "not allow" them, so it might be a side effect of some other change.

In any case, it might be a desirable side effect, as those are invalid URL characters that would need to be encoded, but with proper url-encoding, I don't see an immediate reason.

Also, can you elaborate what are you experiencing that you are interpreting as "not being able to use them"? Do you get an error? If so, which one? Have you checked the logs?

**Comment by acelaya** [comment]
Closing until requested information is provided.

**Comment by tiritibambix** [comment]
Thanks for your answer.

I am away From home for quite a while so I'm sorry I can't answer properly for the moment as I don't have access to the logs.

I can't remember what version it started not working.

As for the error message, it is mentioned in my original post.

**Comment by acelaya** [comment]
> As for the error message, it is mentioned in my original post.

Thanks! I somehow missed that, perhaps I read the message in the email notification from GitHub and didn't realize it had been updated right after.

**Comment by acelaya** [comment]
Ok, so I found when was this introduced. It was the result of this bug report https://github.com/shlinkio/shlink/issues/1901 (you can ignore everythign after my first comment there, because conversation deviated into a feature request not related to the bug itself).

To fix that, [this PR](https://github.com/shlinkio/shlink/pull/1911/files#diff-1590198407073217b1d39ab886681639464e3477b6d21e1d9988431884a75c47R49-R50) was provided, which validates custom slugs to disallow URL-reserved characters as per [this RFC](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2).

I need to do a bit of investigation and think on potential side effects of changing this, or if that decision was wrong in the first place.

**Comment by tiritibambix** [comment]
I'm really glad you're considering looking into this and I'm looking forward to reading you on this matter :)

**Comment by tiritibambix** [comment]
I'm really happy you're considering re-implementing this again :)
