### ISSUE TITLE
Bug failing to create certain links

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#306]
Was trying to make a short link for the below URL but I it fails every time. Chrome console shows a 400 error when trying to make this link.

https://i.imgur.com/QGaM7XA.png

``
https://www.cdw.com/product/Kensington-SD7000-Surface-Pro-Docking-Station-DP-HDMI-Windows-10-dock/5198638?enkwrd=SD7000
``

**Comment by acelaya** [comment]
During installation, Shlink asks if you want to verify all provided URLs and make them fail if they don't return a status 200 (after following redirections).

That URL is returning a 403, which is resulting in shlink returning a 400 and not creating the short URL.

**Comment by acelaya** [comment]
Yes. Open the `config/params/generated_config.php` file, find the `validate_url` config entry and replace the `true` value by `false`.

Then delete the `data/cache/app_config.php` file.

If you are running shlink with swoole (which I suppose you are not since you have just updated to v1.15.0), you will need to restart the service.

And that should be it. There will be no more verifications.

**Comment by tivyhosting** [comment]
How do you run Shlink with Swoole?

**Comment by acelaya** [comment]
It is documented in the readme fle of the project. Look for the "swoole" text there.

I still need to update the website.
