### ISSUE TITLE
Duplicate data in visit_locations 

### ISSUE THREAD

**Issue by TakeMeNL** [shlinkio/shlink#328]
So i have 50 calls made to a shorten link, now i have 50 visit_locations rows for each call from the same ip.
Thats not good right? 

shlink dev-master checkout

**Comment by acelaya** [comment]
Yes, definitely, that's not properly normalized, and it's also a known issue https://github.com/shlinkio/shlink/issues/26

However, this is a small optimization, and changing it would require an extra check on every visit resolution. That's why it was closed and never implemented.

I don't discard doing it at some point, but it's not high priority.

**Comment by TakeMeNL** [comment]
Oke thats fine, but i can understand why #307 maybe is related to this?
Doctrine objects are not resource friendly and not often updating results is high memory usage.
Which anno now is not that of a big deal, but when you run it in a hosted container or hosted vm with limited resources it can be. 
Personally i find it database garbage
