### ISSUE TITLE
asynchronous webhook or events when user visit url

### ISSUE THREAD

**Issue by mesilov** [shlinkio/shlink#338]
In documentation https://shlink.io/swagger-ui/index.html I can't find events or webhooks.

I need to receive the basic event when client visit URL on my API endpoint.

**Comment by acelaya** [comment]
I have mixed feelings about this. On the one hand I think it would be something nice to have, but it would also become a feature complex to maintain if done properly.

I would discard making synchronous calls to a callback endpoint, because it would delay redirecting visitors.

It could be done so the event was published somewhere (redis, Kafka, a queue of some kind...), and services could subscribe if needed, but it would introduce a lot of complexity in order to support different use cases.

It would also be hard to configure by end users if done this way.

I won't close this, but I will need to think about it (feedback is more than welcome).

It won't be a priority for now.

**Comment by mesilov** [comment]
@acelaya 
Maybe we can add event-model in a core product and that's all. Example: phttps://symfony.com/doc/current/components/event_dispatcher.html 

If user needs asynchronous webhook they can use event model to store events in a queue for his environment. And core-product will be small and clean

**Comment by acelaya** [comment]
Maybe I'm missing something, but I don't see how the Symfony event dispatcher could help here. It works at code level, while usually, when you "consume" shlink, you are not writing any code.

Could you clarify?

**Comment by mesilov** [comment]
@acelaya  yes, you right. 
Maybe you can add a feature to send events to Mercure?
see https://symfony.com/blog/symfony-gets-real-time-push-capabilities

**Comment by camaxtly** [comment]
@acelaya, nice feature, I really need it too

**Comment by D-Visigo** [comment]
+1 this is a feature I would really appreciate.

**Comment by acelaya** [comment]
I will finally add a simple implementation for this, but it will work on swoole-based instances, since it allows asynchronous tasks to be run just after returning the HTTP response.

**Comment by acelaya** [comment]
Update regarding this feature.

Version 1.21.0 will include a simplified version, which will make Shlink send POST requests with visits information (as a JSON payload) to a list of configured webhooks.

It will do it only when serving Shlink with swoole.

In the future I will extend the feature so that Shlink can be integrated with a mercure server (thanks for the info @mesilov :wink: ). This will not only improve integration with third party services,but also very useful for shlink-web-client.

> Related issues: https://github.com/shlinkio/shlink-web-client/issues/148, https://github.com/shlinkio/shlink/issues/524

**Comment by acelaya** [comment]
I have just tagged [v1.21.0](https://github.com/shlinkio/shlink/releases/tag/v1.21.0), which includes this feature.

I will document how this works, but for now, you can check the release notes to see how it is implemented.

**Comment by acelaya** [comment]
For anyone interested, I'm glad to say that I have just finished implementing the integration with [mercure](https://mercure.rocks). It will be part of Shlink 2.2

I will work next on making a good use of that from shlink-web-client.

More info can be found here: https://github.com/shlinkio/shlink/issues/524

/cc @mesilov @camaxtly @D-Visigo
