### ISSUE TITLE
Question: Multi instance - what are the consequences of getting it wrong

### ISSUE THREAD

**Issue by jasoniangreen** [shlinkio/shlink#375]
Hi,

On the docker image repo you mention some considerations when running multiple instances of the service. I would just like have an idea of what it would mean if you messed up the two points. 

1. What happens if instances are running with different shortcode charset?
2. What happens if instances have out of sync versions of GeoLite2?
3. Also I notice that it downloads the GeoLite2 database every time the docker runs. Could that be a problem if it is down, are we supposed to have an account with them? Maybe we should cache a version and attempt to update but still succeed if it is down?

Thanks.

**Comment by jasoniangreen** [comment]
Oh and @acelaya one more....

When I setup a config file for `keys.config.json` and I look at the contents of `/tmp/shlink.keys`, the keys are still different from each other. Is that to be expected? How can I confirm that the config file is actually being used and the charset and secret being used are the ones from `keys.config.json`.

Sorry if this is not the right way to ask these questions.

**Comment by acelaya** [comment]
Hello @jasoniangreen. Don't worry, this is definitely the right way to ask :smile: 

Let me quote your questions:

> What happens if instances are running with different shortcode charset?

Well, it could be that nothing happened and shlink worked just fine.

When the docker image is run for the first time, it generates a shuffled version of the base62 charset (`0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`), and uses it to generate short codes.

Those short codes are generated based on their autoincrement primary key (something that I will probably change, but that's how it is right now), and the shuffled charset.

If every container was sharing the database but not the charset, you might see "different" short codes (they look sort of consecutive when using the charset, one of the reasons I want to change the algorithm).

The possibilities to have a collision here are quite low, so if you don't mind the consistency, you should be good to go.

> What happens if instances have out of sync versions of GeoLite2?

Having out of sync databases is not really the issue. If you manage to update all of them, even if they are not updated at the same time, there should be a veeeery low impact (maybe if you have hundreds of thousends of visits...).

The reason I recommend sharing the GeoLite2 database is because of the way container orchestration tools usually work.

For example, if you configure a kubernetes cron job to run the database update, it will spawn a new pod, run the command on it, and then kill it. The result will be the database being updated just in this new pod, and not in any of the pods running as part of a deployment.

However, I'm now realizing that if you follow this same approach to process visits, the new pod will download an updated database before processing anything, so this might not be an issue :thinking: 

In fact, I will probably make the command update the database if it is older than 7 days (for example), so that updating the file does not need to be scheduled.

> Also I notice that it downloads the GeoLite2 database every time the docker runs. Could that be a problem if it is down, are we supposed to have an account with them? Maybe we should cache a version and attempt to update but still succeed if it is down?

Yep, this is absolutelly an issue I didn't consider. I will check what could be the impact, and make sure a network issue does not make the container run fail.

> When I setup a config file for keys.config.json and I look at the contents of /tmp/shlink.keys, the keys are still different from each other...

Yes, don't worry about that. The container generates those anyway, however, the provided config file then overwrites those. It's something I want to improve because it is not very intuitive.

Shlink generates a cached config file with all the loaded files which will use after the first execution. In order to verify the correct keys are used, run these commands:

    docker exec -it <shlink_container> cat /etc/shlink/data/cache/app_config.php | grep shortcode_chars

    docker exec -it <shlink_container> cat /etc/shlink/data/cache/app_config.php | grep secret_key

If you see the correct values, you should be good to go. If not, delete that file and try again.

(I have used docker for the example, but you might need to use some other tool depending on the way you run your containers)

The conclusion is that I still have to implement some improvements to make shlink easier to use with multiple containers or in a cluster. It is still not completely stateless.

I hope that answers your questions.

**Comment by jasoniangreen** [comment]
Thanks for the detailed answers, very much appreciated.

Ok so we only have to download the geolite2 database when we are updating the locations/visits? And that only has to be done on one container, because it is updating the database so doesn't need to run on all. Plus all of that is only if you want to see visit geo information. At the moment we just need redirection to work.

Also, you explained the charset option, but there is also a SECRET_KEY.... If I am not mistaken, this is for validating authenticated users. If I am only using the API key to create shortcodes, then that secret key doesn't really matter, does it?

**Comment by acelaya** [comment]
> Ok so we only have to download the geolite2 database when we are updating the locations/visits? And that only has to be done on one container, because it is updating the database so doesn't need to run on all. Plus all of that is only if you want to see visit geo information. At the moment we just need redirection to work.

Yep.

> Also, you explained the charset option, but there is also a SECRET_KEY.... If I am not mistaken, this is for validating authenticated users. If I am only using the API key to create shortcodes, then that secret key doesn't really matter, does it?

The secret key is actually used for a deprecated auth method.

If you are only using the shlink-web-client v2.x (which is actually the one which is served when accessing https://app.shlink.io), then you don't even need to take the `secret_key` param into consideration.

**Comment by jasoniangreen** [comment]
Ok, thanks, that answers my questions, so I will close this issue now.
