### ISSUE TITLE
Moving from http to https

### ISSUE THREAD

**Issue by captainAldi** [shlinkio/shlink#386]
first time i install shlink in my server i choose http, now i just upgrade my web server using SSL so my web can use https.. but, the short url that generated still using http how to change it to https also ?
thanks

**Comment by acelaya** [comment]
You have to do two things:

* Open the file `config/params/generated_config.php`, and update the `schema` option setting https instead of http.
* Delete the `data/cache/app_config.php` file (this cached the merged config, and will hold the old value. Deleting it will force shlink to regenerate it on the next request).

That should be all.

**Comment by captainAldi** [comment]
Thanks, it worked !

**Comment by acelaya** [comment]
Glad to hear that :)

I'm planning to include a CLI command that simplifies this. It will eventually be there.

**Comment by noook** [comment]
Hi, I am facing the same issue, however I can't find those references files in my docker container. Latest version: 4.4.0
