### ISSUE TITLE
cant short link from linkedin

### ISSUE THREAD

**Issue by captainAldi** [shlinkio/shlink#394]
when i want to create short link from linkedin it says 

"An error occurred while creating the URL :( "

and when i try on cli, the error is

 [ERROR] Provided URL "...." is invalid. Try with a different one.

but not with others links.. it can make the short url...

why it's that possible ?

thanks before

this is the log that i quote 

`[2019-04-09 12:09:39] Shlink.WARNING - Provided Invalid URL.
GuzzleHttp\Exception\RequestException: Unsuccessful request: `GET https://www.linkedin.com/company/xxx` resulted in a `999 Request denied` response:
<html><head>
<script type="text/javascript">
window.onload = function() {
  // Parse the tracking code from cookies.
  v (truncated...)
 in /home/infra/cobaShlink/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
`

**Comment by acelaya** [comment]
As you can see in the logs, that URL is returning a not-2xx status.

If you configured shlink to validate long URLs, it fails to create short URLs when that happens.

**Comment by captainAldi** [comment]
so, how to avoid this thing happen and creating of the short url (with that link) success ?

**Comment by acelaya** [comment]
You will have to change the config, and since there's no command to do it automatically (yet), you will have to do it manually following these steps:

* Open the `config/params/generated_config.php` file and replace the value of the `validate_url` option from true to false.
* Delete the `data/cache/config_cache.php` file.

That should be all. You should be able to register any URL after the change.
