### ISSUE TITLE
Support prefixing DB table names

### ISSUE THREAD

**Issue by bdotzour** [shlinkio/shlink#399]
Would it be possible to provide a configuration option to provide a prefix string to be used on the table names that are created?  This would allow reusing an existing database schema rather than having to create a new one.

**Comment by acelaya** [comment]
It is something I have considered several times and it probably makes sense.

I will investigate the effort required to get it done.

**Comment by acelaya** [comment]
Hey @bdotzour 

I know this has been around for a while, but it's hard to find the time to work on everything.

I think I might have found a way to have this while I was trying to bring support for postgres schemas.

I will get it implemented for v2.2.0

**Comment by jenkin** [comment]
Hi @acelaya , any news on this?

**Comment by acelaya** [comment]
It's a bit trickier than anticipated, that's why I ended up removing it from v2.2 milestone.

Having the table get a prefix is reasonably easy. However, getting the config injected in the migrations is a bit trickier.

I'll try to investigate a bit further, and see if I can get it squished in v2.3

**Comment by jenkin** [comment]
Thanks!

**Comment by acelaya** [comment]
I haven't found a simple way to do this, and it doesn't seem to be driving too much attention.

Because of that and in order to narrow down the amount of supported features, I'll close this.

**Comment by mvandenabeele** [comment]
Hi

I was looking for a way to add shlink to an existing database because I have no available databases left in my hosting plan, and I don't want to host it myself. Prefixing tables would be great for this. I see the tablePrefix is commented out in modul/Core/functions/functions.php. In this discussion, it is stated that it was left out because getting the config injected was tricky, but it was done for the $schema on line 61; one line above the tablePrefix one. What needs to be done to get this in a future release? How can I help with that?

**Comment by mvandenabeele** [comment]
code as I see it, would be like

`function determineTableName(string $tableName, array $emConfig = []): string
{
    $schema = $emConfig['connection']['schema'] ?? null;
	$tablePrefix = $emConfig['connection']['table_prefix'] ?? ""; 
	
    if ($schema === null) {
        return $tablePrefix.$tableName;
    }

    return sprintf('%s.%s%s', $schema,$tablePrefix, $tableName);
}`

**Comment by acelaya** [comment]
As I mentioned in my comment, the part I still haven't figured out is dynamically determining the prefix during migrations.

**Comment by mvandenabeele** [comment]
I'm not entirely sure what you mean by 'migrations'. Is it when a server gets updated? As the default prefix would be an empty string, I don't see the issue, but I'm sure there's more to it if you say so. If you're willing to explain in a bit more detail, I'd like to have a stab at it.

**Comment by acelaya** [comment]
Migrations are a mechanism used to be able to provide programmatic updates for the database, mainly during Shlink updates, yes.

In those, I have to reference table names, therefore, I need to have access to the generated application config in order to know what's the prefix.

Shlink uses a project called doctrine migrations for that.
