### ISSUE TITLE
More metadata than just the existing 'tags'

### ISSUE THREAD

**Issue by D-Visigo** [shlinkio/shlink#412]
I love this project, and thank you very much for building it.

**Feature request:**
Additional metadata 'slots' accessible via shortLink creation API and inserted into DB

**Issue:**
Am using Grafana to analyze the data from the same SQL DB as Shlink and display click statistics, global visit maps, etc. and it is difficult to filter on multiple tags with existing DB structure.

**Proposed solution:**
Add the ability to include new metadata 'labels' and values in the link shortening request, not just tags. Create table column if does not exist already, and store the value.

Solution 1:
{
  "longUrl": "http://some.site/page.html",
  "tags": [
    "string"
  ],
  **"campaign": [
    "string"
  ],
  "userSegment": [
    "string"
  ],
 "episode": [
    "string"
  ],**
  "validSince": "string",
  "validUntil": "string",
  "customSlug": "string",
  "maxVisits": 0,
  "findIfExists": true
}

Solution 2:
{
  "longUrl": "http://some.site/page.html",
  "tags": [
    "string"
  ],
  **"metadata": [
 "string":"string",
 "string":"string",
 "string":"string"
]**
  "validSince": "string",
  "validUntil": "string",
  "customSlug": "string",
  "maxVisits": 0,
  "findIfExists": true
}

Solution 2 seems much simpler, but I'm not sure I could easily use it in SQL queries afterwards.

You can always tell me to get more robust with my SQL side of things, and perhaps doing something like https://stackoverflow.com/questions/44378087/sql-tag-list-and-tag-filtering is the answer.

Thank you for considering this.

**Comment by D-Visigo** [comment]
I just read that PostGres supports arrays, and I know that Shlink supports PostGres as a custom backend, so perhaps that is an 'easier' solution - to implement Solution 2 above with native PostGres handling of the array of the 'metadata' value, and I can query and filter on it with the DB queries.

**Comment by acelaya** [comment]
Hello @D-Visigo, and thanks for the kind words :)

Regarding your feature request, I think what you are asking for is not the right solution to your problem.

I could add support for dynamic key-value metadata, but I would never do it by dynamically creating table columns. Instead, I would create an external table for that purpose, so you would end up with the same problem you have with tags.

I think that the problem here is that you are relying on SQL for your metrics, instead of the public REST API, which is more suitable for that.

The first thing that I'm going to suggest is that you use shlink-web-client, a frontend which does everything you have mentioned above. You can either host it yourself, or just use the one here https://app.shlink.io

If you still want to go with your grafana solution, then I'll suggest following what's explained in the stack overflow article you shared.

I hope you can get it sorted out with this. Thanks for using shlink :)

**Comment by D-Visigo** [comment]
@acelaya Thank you Alejandro for your reply.

I am trying to create specific KPI dashboards for certain combinations of factors. The link shortening is part of a larger ecosystem of SMS messages being sent and videos being watched, and I am trying to give a 'birds-eye' view of all of the important metrics at once, and over time... hence Grafana :)

I already have the Shlink front end running and use it to administrate or 'check' on things... and while it's a brilliant tool for Shlink, it's not enough for the use case I have :)

Here are a few examples of things I am trying to do that seem impossible with the Shlink front-end, even just using data from the Shlink 'universe':

View visits within the last x days, not including visits with the user agent "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0" which is a look-ahead/Open Graph URL preview visit... not an actual 'click'.

View aggregate visit statistics by a combination of tags. For example, for tags X + Y, how many users have clicked (and show click activity)

[Other stats I am putting together:](https://www.dropbox.com/s/rh352x0wsovpfd0/GV%20Link%20and%20Click%20Stats%20-%20Grafana.pdf?dl=0)


Number of links created this week so far
Number of visits this week so far
Number of unique users that have clicked this week so far
What % of users have clicked (number of unique clicks / Total number of subscribers - number of SMS errors)

Apologies if this is too much information, but I wanted to be clear about why I was going down this path 👍 

Last question:
Do you have any idea of how many links Shlink can handle? I add about 100 per week on average, and have over 800 links right now. Is there an upper limit I should be aware of?

Thank you again for making such wonderful software.

**Comment by acelaya** [comment]
Hey, that's a cool use case :)

In order to achieve that I don't see any other way other than the REST API, I'm afraid. Although I will probably steal some ideas to include in shlink-web-client.

Regarding the limit you mention, shlink does not have any hard limits, but maybe you want to check the capacity of the database engine. That's the only thing that could be a bottleneck.
