### ISSUE TITLE
Shortlink Preview generates 500 error

### ISSUE THREAD

**Issue by benhartwich** [shlinkio/shlink#520]
#### How Shlink is set-up

* Shlink Version: 1.19.0
* PHP Version: 7.3.11
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary

When I open the preview of a created sharing link I can´t see the preview, but the chrome console tells me that there was a 500 error

#### Expected behavior

I should see the image / screenshot of the preview website

#### How to reproduce

Open the preview

**Comment by benhartwich** [comment]
I cannot see any error at the nginx or shlink/data/log folder when this action happens. Is there any way to debug it?

**Comment by acelaya** [comment]
The preview generation has always caused more problems than anything else. It usually produces hard to debug errors.

It depends on a native library which in turn depends on other native libraries to exist in host machine. Even more, included library does not work on anything other than Linux (and probably, not all distribution).

Because of this and due to the fact that it is not a widely used feature, it was deprecated a few versions ago.

No more work will be done regarding preview generation, and it will be removed from shlink on v2 in order to focus on more useful stuff.

I'm sorry I cannot give you better news.
