### ISSUE TITLE
[Request] Add "shlink-web-admin"

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#531]
ATM Shlink aswell as "shlink-web-client" is installed at my Server.
My Setup is like this:

https://l.domain.tld (shlink)
https://links.domain.tld (shlink-web-client)

https://l.domain.tld --> https://www.domain.tld (as to not hit the Shlink Domain itself)

But I somehow miss a Web-Client-Admin for each Shlink Server. With this web-admin I would like to be able to Backup/Update/Restore/Manage the Shlink Server.

The Shlink-Web-Admin again could be on any other random Domain or maybe just on
https://l.domain.tld/admin

**Comment by acelaya** [comment]
Hey @MartinH0 

Thanks for the suggestion. I have to admit that it's something I have considered myself several times.

Even though it's something that would be very useful, it would require a ton of work.

It would require a new set of API endpoints for management tasks, a more complex authentication and authorization system, and a new web front end.

It would also make the general setup more complex to prepare, since it would require tinkering a new piece in the puzzle.

That's why something like this has never happened yet, and it's not very likely to happen in a near future. I simply don't have the capacity, and prefer to spend my time on improving shlink itself.

However, adding more CLI commands to shlink or it's installer tool could be a more realistic option, and I would be open to investigate that path.

Thanks for your understand.
