### ISSUE TITLE
Is the PHP Module "swoole" required or not?

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#532]
My Setup:
Shlink v1.20.0
Shlink-Web-Client: v2.2.2
OS: Debian 9.11
Panel: Plesk 18.0.20
PHP: 7.3.11

I do not have swoole installed but everything is working fine untill now.
I have not installed Shlink with Composer as it did not work (becasue of swoole) so I just installed it with the .dist package. Worked fine!

Not I want to install "shlink-ip-geolocation" but as there is just a manual for installing it with composer.
Not this fails again due to not having swoole installed.

Now my question is: Is swoolöe required, as its working flawless without it or is it not required and just better for performance?

**Comment by acelaya** [comment]
Swoole is not a requirement. If you decide to serve shlink with a classical web server, it's just fine.

It's true that composer fails when trying to manually build shlink if you don't have swoole, but that's because one of shlink's dependencies marks it as required. It's something I want to investigate, but I don't think there's an easy solution.

Usually, you just need to download the dist file (and in fact you should), so it should not be a big problem.

Regarding the geolocation library, you don't need to install it yourself, shlink already comes with it out of the box.

Its code was originally part of the main shlink repo but it was split out of it for other projects to be able to use it if they want.

For shlink users, all the required libraries are already there.
