### ISSUE TITLE
No Countries and city shown at statistics

### ISSUE THREAD

**Issue by benhartwich** [shlinkio/shlink#538]
#### How Shlink is set-up

* Shlink Version: 1.20.0
* PHP Version: 7.3.11
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary

When I visit the statistics of shlink shortened URL all countries and cities are shown as unknown. Is there any config at nginx I´m missing or anything other which cause a complete loss of geo identification? It never worked and I´m running shlink since the version 1.19.0. At the updater I´ve seen that the geolite2_db was successfully downloaded. 

How can I debug it further? Is there any php module, which needs to be installed?

I´m self hosting the web client of shlink.

**Comment by acelaya** [comment]
Hello @benhartwich 

In order to locate visits you need to run the `visit:locate` command manually.

Since locating visits is a bit resource and time consuming, is not done add party is the visit registration.

Instead, the recommendation is to have some scheduled task that updates that from time to time.

Everything is explain here https://shlink.io/documentation/long-running-tasks/

**Comment by benhartwich** [comment]
Thanks, solved my problem.
