### ISSUE TITLE
Main Cron which executes all other Crons

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#543]
#### Summary

Would love to have a main/shlink-cron

Something like:
`* * * * * php /var/www/vhosts/domain.de/httpdocs/shlink/artisan schedule:run >> /dev/null 2>&1`

(ofc adopted to shlink, this example is from a Laravel App)

This cron should execute all other crons, so the User just have to setup one cron which then will execute the others which makes things much more easier.

It could for example execute:

1. `/path/to/shlink/bin/cli visit:update-db`
2. `/path/to/shlink/bin/cli short-url:process-previews`
3. `/path/to/shlink/bin/cli visit:locate`

And of course also other crons.

As the main Cron is set to every minute (`* * * * *`) it can execute all other crons aswell.

For example:

`0 0 7 * * php /path/to/shlink/bin/cli visit:update-db`
`0 0 7 * *` = (at the 7th day of a month) which would guarantee it downloads the new DB after it releases

But this would make things for us users much more simple. Also some host applications on shared hosted enviroments where the number of crons is limited

**Comment by acelaya** [comment]
Hey @MartinH0 

Maybe I can consider that in the future if needed, but for now, is probably not going to be needed, for this reason.

The visit:update-db command is deprecated. A few versions ago I updated shlink logic so that it transparently downloads the DB when trying to locate visits, so you no longer need to have it added as a scheduled task.

Also, everything related with previews is also deprecated, which leaves you with just one cron job to configure, visit:locate, and even that one could be removed if you are using swoole (which is highly recommended if your hosting supports it).

Problem solved :)
