### ISSUE TITLE
Question about 2 fields in Shlink setup configuration

### ISSUE THREAD

**Issue by kuerious** [shlinkio/shlink#602]
#### How Shlink is set-up

* Shlink Version: **1.21.1**
* PHP Version: **7.2**
* How do you serve Shlink: **Self-hosted Apache**
* Database engine used: **MariaDB**

#### Summary

I am running multiple web servers behind a NAT. I've configured everything correctly up to the Shlink server itself, including a subdomain (url.xxx.xxx):

`Internet (url.my.domain) <-> FW/Rtr Port FW 80 <-> Nginx Rev Proxy 80/443 <-> Shlink VM`

The two fields I am most confused about are (a) "Default domain for generated short URLs"; and (b) "What is the path from which Shlink is going to be served?"

(a) Do I specify JUST the "domain.tld", or do I specify "url.domain.tld" here?

(b) By "path" do I specify "/var/www/shlink", or "./shlink", or "url.domain.tld", or what?

I promise, I've been digging a LOT about this, and beyond ONE "how-to" article by LinuxBabe, I've found no help/reprieve for my answer. I DO plan on posting a simplified "how-to" myself and linking it via Reddit and some other sources, ONCE I UNDERSTAND what those two fields mean.

BTW, I've tried a variety of settings for those two fields, but all I get is "An error occurred" messages.

I am:

- using a standard LAMP stack with MariaDB
- installing all pre-requisites, including PHP add-ons and the Open-Java stack
- I have been banging my head on this for two weeks now

**Comment by acelaya** [comment]
Hey @kuerious.

You don't have to apologize for asking. I'm well aware that the documentation is far from perfect and I will improve it based on what you ask :)

Regarding you questions:

> (a) Do I specify JUST the "domain.tld", or do I specify "url.domain.tld" here?

You have to specify the subdomain too. This is used mostly for the API to be able to generate short URLs.

If you plan to serve Shlink under `url.domain.tld` so that you can have short URLs like `url.domain.tld/abc123`, you need to provide the whole subdomain, otherwise, the API would return links like `domain.tld/abc123` instead, which would not reach Shlink.

Of course, you would still be able to manually assemble the short links yourself and Shlink would properly do the redirects, but for integrations (with shlink-web-client, for example), it's best if the proper value is provided here.

> (b) By "path" do I specify "/var/www/shlink", or "./shlink", or "url.domain.tld", or what?

That does not reference the path in the filesystem, but the web path.

Some user don't want to use short domains or subdomains, but instead serve Shlink from a subfolder (which does break a bit the idea behind the whole short domain approach, but who am I to judge).

So for example, if you had a domain `domain.tld` and would like to serve Shlink under `domain.tld/foo/bar`, which would generate "short" URLs like `domain.tld/foo/bar/abc123`, the value you would have to provide for the path is `/foo/bar`.

By default, it is assumed you want to serve Shlink from the root of the domain/subdomain, and therefoore, you can leave the path empty.

**Comment by kuerious** [comment]
No matter what I do, nothing's working. I'm building it in a VM, which allows me to revert to snapshots.

This is the code I used (expires: 1 week):
https://pastebin.com/qg8fpJ6d

Here is how I configured it:
https://i.imgur.com/mKNJ0HC.png

Here is how I ran the instructions:
https://i.imgur.com/kSkNPQd.png

Here is the result:
https://i.imgur.com/0tomvYj.png

**Comment by acelaya** [comment]
It is probably because of this option:

> Use defaults for the remainder of choices until:
> "What is the path..." -> /shlink

If you plan to serve shlink on `http://url.kuerio.us/shlink`, then you have to also provide the path to shlink-web-client, not only the domain.

On the other hand, of you want to serve it from `http://url.kuerio.us`, then you should leave an empty value when answering "What is the path..."

**Comment by kuerious** [comment]
I've tried that. Same result. I am clueless as to what to try next. I honestly tried a LOT.

I've decided to host YoURLs off my webhost instead of local hosting. I really wanted the advanced features of your product (QR codes!? yes!). I don't know what was going wrong.

**Comment by acelaya** [comment]
I think you are pretty close, but I perfectly understand.

I plan to prepare some troubleshooting documentation, with common issues and how to debug and solve them, bit I didn't have the time yet.

Thanks for giving shlink a try.
