### ISSUE TITLE
Support for prefixing short urls

### ISSUE THREAD

**Issue by SteveEdson** [shlinkio/shlink#609]
#### Summary

An option to prefix a short url, to make managing links easier. E.g. I might want to have a URLs like:

http://foo.com/a123
http://foo.com/b123
http://foo.com/c123

Where a, b and c are different categories.

I realise I could do this using the `customSlug` parameter, but I feel this would be easier to manage if it was a built in feature.

Thanks

**Comment by acelaya** [comment]
I'm not sure if I follow you.

What is the idea behind this? You want those links to point to the same destination or be different links by themeselves?

Is this prefix supposed to be autogenerated or something you provide (as you would with a custom slug)?

**Comment by SteveEdson** [comment]
They would all be different destinations. The prefix would be supplied, but the rest of the URL would be generated like normal.

Right now if I wanted to achieve this, I'd have to use a custom slug, but implement the hashing / random string myself etc. 

In my head, shlink would act as normal, but if I prefer was supplied, it'd just put that right before the generated short code.

**Comment by acelaya** [comment]
So you basically want a part of the slug to be common between a group of short URLs, while the rest is random, right?

I assume you want this to ease searching for those particular URLs which have that part in common.

You can already achieve that by using tags. Just create regular short URLs, and apply the same tag to all of them (use the desired prefix as the tag).

Then, you can filter the list by tag (from shlink-web-client, you can do it by clicking on the tag).

Let me know if there's some other use case I'm not being able to see.

**Comment by SteveEdson** [comment]
It's pretty much that, but being able to identify them outside of the system itself. 

Some links will be used on print media for example, and would need to be prefixed with `p`, others come from a communications system and need to start with `c` or `sms` etc. Just to make managing easier, and so a link can instantly be recognised as belonging to which system.

**Comment by acelaya** [comment]
I see your point.

However, this feature would introduce a maintenance cost which is not worth as opposed to the value it would bring to shlink.

Tags are much more suitable for this, and in the future, shlink will have stats by tag, something quite useful for use cases like this one.

And if you want links to be identifiable by themselves, you can always use custom slugs, even though in this case might be a bit cumbersome since you want part of it to be random. Services like this https://onlinerandomtools.com/generate-random-string might help with the task.

In any case, I would still recommend tagging your URLs with the prefix, because it will help you manage them when the list grows.

I'm sorry I couldn't give you any better news, but I'm sure you understand.
