### ISSUE TITLE
Permission denied error when shlink tries to download same GeoLite db more than once

### ISSUE THREAD

**Issue by benhartwich** [shlinkio/shlink#621]
#### How Shlink is set-up

* Shlink Version: 2.0.2
* PHP Version: 7.4.1
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary
The Cronjob: 
`0 * * * *       root    sudo -u shortener /usr/bin/php7.4 /var/www/shortener/htdocs/shlink/bin/cli visit:locate -q`
produces the following error:
`PHP Warning:  PharData::extractTo(/tmp/GeoLite2-City_20200107/GeoLite2-City.mmdb): failed to open stream: Permission denied in /var/www/shortener/htdocs/shlink/vendor/shlinkio/shlink-ip-geolocation/src/GeoLite2/DbUpdater.php on line 70`

**Comment by acelaya** [comment]
It looks like the system user running the app (I guess it's www-data) does not have permissions to write on the /tmp folder (which is weird, since usually any user can write there).

**Comment by benhartwich** [comment]
Yes, you´re correct - I´ve added an user shortener, which is part of www-data group and I see that the tar.gz file of geolite city is downloaded to temp. Has the extracting changed? It worked with the old version like a charm.

**Comment by acelaya** [comment]
Nop, nothing changed on Shlink side. This has been the same for a while.

Maybe PHP 7.4 changed something on regards to filesystem access.

**Comment by acelaya** [comment]
@benhartwich I have been reading some docs in order to find out the root cause for this, and I'm thinking if maybe the file that is being downloaded already exists in your temp dir.

By default, the function does not override it, which could be causing this permissions error if the file already exists.

Can you check if your system has a `/tmp/GeoLite2-City_20200107/GeoLite2-City.mmdb` file, and if that's the case, delete it and try running the command again?

If that is the cause, then it's a bug that would need to be fixed.

**Comment by benhartwich** [comment]
@acelaya : thanks - a folder existed, but it was empty. I´ve deleted it and will report.

**Comment by benhartwich** [comment]
@acelaya : seems to be solved.

**Comment by acelaya** [comment]
Ok. Then the permissions error was probably caused by Shlink not being able to override that existing folder.

I will investigate how to solve that. Thanks for the confirmation :-)

**Comment by acelaya** [comment]
@benhartwich I have not been able to reproduce the issue myself. I guess it was a combination of permissions/user changes or something like that, but in all the tests I've done, folders were always properly overwritten.

What I have done instead is making the installer tool copy the GeoLite db file if exists on previous instance, when you are updating shlink.

This way, shlink will never try to download the same version of the GeoLite db more than once, and since the temp path is different for every version, it will not conflict and therefore, it should not throw any permissions error.
