### ISSUE TITLE
MSSQL support

### ISSUE THREAD

**Issue by akiller** [shlinkio/shlink#626]
#### Summary

Hi,

This project looks really interesting. I was wondering if you were planning to add support for MSSQL at any point soon? MSSQL inside Azure for example is considerably cheaper than MySQL/MariaDB/PostgreSQL from both Azure and AWS' PaaS offerings.

I did try and get it working myself but discovered there was quite a few places I'd need to hook up to make it work and I'm obviously not too familiar with how the project

Thanks.

---

- [x] Document support for MSSQL.
- [x] Add database tests running on MSSQL.
- [x] Make installer allow selecting it as one of the available databases.
- [x] Add driver to docker image.
- [x] Document how to use it with docker image.
- [x] Add it to GitHub issue templates.
- [ ] ~~Make tests against MSSQL to be run on travis, if possible.~~ Will be handled in #657

**Comment by acelaya** [comment]
Well, it has been never a priority, but you presented a really good reason to support it.

Also, the main stopper has always been the difficulty to run tests on it, but I have just seen there's official docker images, which should be more than enough.

So, long story short, yes, I will add support :-)

**Comment by akiller** [comment]
That would be great if you could, I'm happy to help out if I can and test it for you if needed. I'd imagine you can reuse most of your SQL statements though.

For reference an MSSQL basic database is ~£4/month vs ~£20/month for MariaDB etc.

Microsoft have really embraced Docker and made it really easy to use with Visual Studio etc which as a primarily .NET based developer is great!

**Comment by acelaya** [comment]
If everything goes as expected, I shouldn't need to do much, since the database abstraction used in the project already supports mssql.

I will need to add support for the configuration though, which should be easy.

I will also make the database tests to be automatically run against this db engine, the same it's done for the rest.

**Comment by acelaya** [comment]
Hey @akiller 

It looks like supporting mssql is going to be harder than expected.

Apparently, the native driver cannot be compiled on Alpine linux, which is what Shlink's docker image is based on.

That means that, not only it is not going to be possible to make the docker image work with a mssql database, but also, that I cannot easily setup dev/testing envs based on alpine images (as I do for everything else), in order to run automated tests using a mssql database.

The first problem is not that big (I could just document that it is not possible to use mssql together with the docker image, while you still can do it if you are hosting Shlink manually), but the second one is going to make things harder.

I will continue investigating a bit more. Also, they state here https://github.com/Microsoft/msphpsql/issues/300 that they will support Alpine end of this month or beginning of the next one, but the issue was opened 2 years ago, which makes me be a bit sceptical.

I will also consider other options, at least for non-docker users.

**Comment by akiller** [comment]
@acelaya thanks for investigating this. That's a shame, hopefully Microsoft will pull through and get it released soon. Certainly if it's only a couple of months away it's worth waiting.

I guess in the unlikely event they decide to not release it another solution would be to do what projects like [Traefik](https://github.com/containous/traefik) (which is great) do and release versions with different base images. E.g., having a shlink-alpine and shlink-ubuntu. It's probably too much work for you for one use case though. I might give it a try if Microsoft don't provide support.

For what it's worth we're using MSSQL with Python on an Ubuntu 18.10 base image using this in our Dockerfile:

```dockerfile
FROM ubuntu:18.10

# MSSQL ODBC driver
RUN DEBIAN_FRONTEND=noninteractive && \
	apt-get update && \
	apt-get install -y \
		apt-transport-https \
		gnupg2 \
		curl && \
	curl -L https://packages.microsoft.com/keys/microsoft.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1  apt-key add - && \
	curl https://packages.microsoft.com/config/ubuntu/18.10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
	apt-get update && \
	ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc unixodbc-dev && \
	apt-get remove -y curl gnupg2 && \
	apt-get remove -y apt-transport-https curl gnupg2 && \
	rm -rf /var/lib/apt/lists/* && \
	apt-get -y autoremove && \
	apt-get -y clean
	
```

**Comment by acelaya** [comment]
In one of the last comments they say the work on supporting Alpine is already in progress, so I hope it doesn't take as much as "a couple of months" (I hope it's less 😅)

Regarding your proposal of having multiple docker images, it's something that will probably need to happen anyway.

Currently the image has drivers for both MySQL/mariadb and postgress. Supporting mssql will force the image to have three sets of drivers with their respective dependencies, when end users will likely never use more than one of them.

In order to reduce image size, I will probably have to split the image, so I could make the one for mssql to be based on other system if support for Alpine gets delayed.

Let's give them a couple of weeks and then decide.

**Comment by akiller** [comment]
Unless it adds several hunderd MB's to the image bandwidth and disk space are cheap I guess but I appreciate wanting to keep the images learn.

The over-engineering thinker in me wonders if you might benefit from having a base Shlink docker container that communicates with another container using gRPC/REST (gRPC will be faster) and that container provides the database implementation.

This would allow anyone to write a plugin for whatever database provider they liked using whatever base image they liked and whatever language they liked.

**Comment by acelaya** [comment]
Yep, that's a little bit overkill :sweat_smile: 

Contributions are very rare, so I prefer to tackle those in case a requirement appears, rather than adding such maintainability debt just in case it is sometimes required.

**Comment by acelaya** [comment]
@akiller they ahe actually released the driver for alpine, and I have started to do some testing.

While I defenitelly got to get it compiled, I'm now getting another error while trying to run the tests, which is also related with alpine. I willl continue investigating.

**Comment by acelaya** [comment]
Ok, never mind. I managed to get it working :smiley: 

I will work on everything else, but this looks promising.

**Comment by akiller** [comment]
I'm shocked Microsoft released something broadly on time!

That sounds like great news thanks for the update. If you get it to the point where you would like it testing by a human let me know.

**Comment by acelaya** [comment]
I will probably release some kind of beta once that's finished and let you test it.

**Comment by acelaya** [comment]
Hey @akiller 

I have good news. I have finished integrating Microsoft SQL Server on Shlink. The docker image will include a driver and I have succesfully been able to run all the tests against it, with no errors, which means no code changes are needed.

I have then been run a Shlink instance against a mssql database and everything worked smoothly.

The best thing is that I have changed some things on the docker image, and even though it now includes one extra database driver, it's even smaller than the image for v2.0.5

The only thing missing is updating the installer so that it offers using mssql as the database engine. You can expect a beta version with preliminary support for mssql to be released this weekend.

**Comment by acelaya** [comment]
@akiller I have just merged the branch which adds support for MicrosoftSQL. Let me know if you are going to have time to test it, in which case I will release a beta version.

If you don't have time at the moment, the feature will be available as part of Shlink v2.1.0 which will be released in a few weeks from now.

**Comment by akiller** [comment]
That's brilliant, thank you, and good news on shrinking the image too!

I've had to disable Docker on my machine temporarily so I can do some work in vmware (Docker on Windows uses Hyper-V which won't work alongside other hypervisors). Once I finish it I'll give it a test and some feedback; it should be within the next couple of days.

**Comment by akiller** [comment]
I'm really sorry for taking so long to get back to you - the world's gone a little crazy. Hope you're staying indoors and coding and not going outside!

The good news is I've finally tried your [latest Docker image](https://hub.docker.com/layers/shlinkio/shlink/latest/images/sha256-43d5a5b686f64e1b4d67fd4bdfcbaf54296efffb70dd5c39469bb96b488ce487?context=explore) on an Azure SQL database and I think everything is working fine which is great news!

I am having one issue, and I don't think this is a MSSQL issue but I could be wrong; when I start the image it tries to apply database migrations but fails because it doesn't automatically accept the warning by passing in a y.

I was able to get around it by starting the container and overriding the entrypoint (docker run -it --entrypoint /bin/sh ...) and manually running doctrine-migrations.php and accepting it, then commenting out all the migration code in docker-entrypoint.sh but it isn't an ideal fix. This was on a fresh database, so the migration process started from database version 0.

> WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)
> 
>   Aborted
> .
>   migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]

**Comment by acelaya** [comment]
Hey!

Thanks for getting back to me. I'm glad to know it works fine.

As you said, the other problem is not related with MsSQL specifically. It's something I also experienced once, but then I couldn't reproduce it anymore, so I ended up not doing anything.

Gladly, it should be easy to fix. I will create another ticket.
