### ISSUE TITLE
Running "/bin/cli visit:locate" not working for old calls.

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#639]
#### How Shlink is set-up

* Shlink Version: 2.0.3
* PHP Version: 7.4.2
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB

#### Summary

I think that geolocating should work from default, OR even backwards with old IPs as they in most cases do not change their location as they are bounded to an area.
So I just run `/bin/cli visit:locate` then the GeoLite2 database was updated (or just downloaded right then) and IPs did get processed.
But for old calls its not showing where they came from.
When I call a link (after first time ran the visit:locate) then location is working and very precise also.

Do you think it would be a big deal of shipping shlink with a GeoLite2 DB by default?

I once set up a GeoLite2 DB aswell (about 2 years ago) see here: https://ip.hotmann.de
And never updated it. Its still very very precise! I just tell you this as I think updating it is very good, but getting a old version shipped by default would not be a big loss as even old very old versions are precise enough for "not having anything to do" and getting it by default.

Just saying, maybe this idea is dumb but I think most people would like "out of the box GeoLocation" even if it is not 100% precise. If someone wanna have it regularly updated and precise he will implement the cron (which I did)

But the point why I ask for this is:

Old link-calls would have a Geo Location even with a not 100% accuracy but now they are missing at all.

Is it a bug, that old Link-Calls are not getting located afterwards or is this meant to be like this?

**Comment by acelaya** [comment]
I think you have a misconception about what the visit:locate command does.

It has a secondary task, which is downloading the GeoLite database file if it does not exist or is too old, but it's main task, once the file is there, is to match IP addresses from visits to the values in the GeoLite file.

So, even if shlink was shipped with a GeoLite file, you would still need to run the command on a regular basis to avoid having "unknown" visits.

That said, it should be able to locate any visit, regardless how old it is.

Maybe you had a lot of unlocated visits and the command is just taking too much time or getting stuck somehow?

I would recommend you manually run this command in order to see any possible error output. Run it with the `-vvv` flag so that you get as much feedback as possible. `/bin/cli visit:locate -vvv`.

You can also check the logs, in the data/log folder. Maybe there's some error there.

**Comment by MartinH0** [comment]
You are right I missunderstood the command. I thought the lookup for the location is getting done by the call (eventbased) but instead its the Cron (timebased) which looks it up. And will also update the DB if needed.

Yes in the Log is something.

```
[2020-01-30T16:52:32.370778+00:00] Shlink.INFO - Successfully acquired the "visit:locate" lock.
[2020-01-30T16:52:32.370908+00:00] Shlink.INFO - Expiration defined for "visit:locate" lock for "90" seconds.
```

Over and over again. Thats why I added to the Cron the `-q` attribute to not make it trashing the Log. But nothing more.

`/bin/cli visit:locate -vvv`
Returns the same as:
`/bin/cli visit:locate`

It just states:
`[OK] Finished processing all IPs` (on green background)

But when I load the backend again it shows me the locations (country and city) are "unknown"

**Comment by acelaya** [comment]
If it says "finished processing all IPs", it means shlink already went over all the visits. Those that still appear without a city and county, are usually because they were not found in the GeoLite file.

However, there shouldn't be a lot of those, unless actual IP addresses are not properly reaching shlink. That can happen if there's some kind of NAT/proxy/gateway in front of shlink which is not propagating the real address from the consumer.

Could you manually check the values of the "remote_addr" column in the visits table of your database?

**Comment by MartinH0** [comment]
I checked all IPs from "remote_addr" manually..
They are valid public IPs (last digit cut off but thats ok)

All Calls do have a IP aswell.
But on some links (all calls before implementing the cron) are shown "unknown" but even GeoLite2 can resolve them.

Is there a function to "re-resolve" them?

Just saw in the table "visit_locations" everything is empty.. means:
Before I implemented the cron it filled it with empty things a zeros for lat & lon but is not correcting it now.

**Comment by acelaya** [comment]
That was my second guess.

There probably was some error at some point (hard to say what exactly) that made shlink think those addresses were not found, and they were marked as already located to prevent them from being processed over and over.

In order to force those to be located again, you will have to remove the foreign keys pointing from the visits table to the visits_locations one, for those which are empty.

I will prepare a script for you later when I'm in front of the PC.

**Comment by MartinH0** [comment]
Would even be nice if the cron could also check (maybe just once a hour not all the time!) if there are IPs it could not resolve/locate and re-checks them.

Like this Shlink will keep the DB clean and up to date itself.

every min it checks for new IPs
once a hour it will "reset" unsuccessfull lookups and then they will get looked up again the next time.

You think this is possible?

**Comment by acelaya** [comment]
Yep, I will have to figure some way to recover from situations like this, but that will be tackled separately.

**Comment by acelaya** [comment]
Hey @MartinH0 

In order to force the visits to be processed again, do the following:

* First do a backup of your database.
* Then run this query:
    ```sql
    UPDATE visits SET visit_location_id = NULL WHERE visit_location_id IN (
		SELECT id 
		FROM visit_locations 
		WHERE country_name="" 
		AND region_name="" 
		AND city_name="" 
		AND lat=0 
		AND lon=0
    );
    ```
    It will unlink all visits that have ben geolocated to empty locations.
* **Optionally**: Run this query, which will delete all orphan locations that were unlinked with previous query:
    ```sql
    DELETE FROM visit_locations WHERE id NOT IN (
		SELECT visit_location_id FROM visits WHERE visit_location_id IS NOT NULL
    )
    ```
* Finally, run the `visit:locate` command again. If there were a lot of visits on empty locations, it might take a few minutes to finish.

A definitive solution will be provided when https://github.com/shlinkio/shlink/issues/641 is implemented, but at least you will have asll you existing visits located for now.

**Comment by MartinH0** [comment]
I will do so and report back.

Thanks!

**Comment by acelaya** [comment]
Hey @MartinH0 

Sorry I didn't get back to you sooner. Since you edited your existing message, I didn't get a notification.

I'm glad that worked.

And yes, I think it should be possible to somehow automate the geolocation retry from time to time.

As per those addresses that couldn't be located, it's hard to say, but a small amount can be expected.

**Comment by acelaya** [comment]
@MartinH0 I have just merged a PR which adds the flaggs `--retry` and `--all` to the `visit:locate` command.

It will be part of v2.1.0, which I'm about to release (as soon as some builds pass).

I will think how to amutomate the retry from time to time for one of the next releases, but for now, you can do it manually if you think something was wrong.
