### ISSUE TITLE
[Feature] Option to activate/deactivate IP anonymization

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#640]
#### Summary

Atm **all IPs** are getting stored with the last block censored like: 111.111.111.**0**
But there is no option (at least I dont know any) to turn this off.
This anyway can be default turned on, but for me as I send a lot of documents to people from the same area and in the end I cant see exactly from where they called the Link.
So for me this is a problem.

So there are two ways of solving this, btw two options that makes sense.

1. IP anonymization BEFOR located
2. IP anonymization AFTER located

If someone wanna be EU GDPR conform could turn option 1 off and option 2 on and would be save.
As the IP gets tracked, but its just possible once.
Its not "ok" (well it is but just with a valid reason) to store IPs not anonymized but before storing it you can still locate them for getting better results as the last Block often gives you much better accuracy.

Also for later trackings (if a IP could not be located) it could also be stored un-anonymized as later location tracking will be not accurate.
If you delete the last block you mostly just always get the next big town (for me stuttgart) but its 50km away from where I'm and I know some (free online) services being able to track me down at about 20km which is very good but does not harm me. So tracking/locating the full IP would be a good option as noone can tell your street name or where you live ..

I think it should be in the hand of the user if he wants to anonymize or not. Also I think setting the default to "anonimize" is very good.

**Comment by acelaya** [comment]
I guess it shouldn't be too hard to implement.

A warning here and there telling users that disabling anonimization will be against the GDPR should be enough.

I will plan to get it done for one of the next releases.

However, in my experience, the last octet does not really improve accuracy too much. Do you have any data backing the opposite?

**Comment by MartinH0** [comment]
Happy you ask for.
Do you mean a "Warning" to the Link caller oder "user" like the installer/admin?
I would recommend not telling the Link caller anything about it as in some countrys its completely legal (india/china/russia etc)

Good you asked. To get a bit more into detail it depends on where on the world you are, so people in italy & switzerland are gettuing dramatic wors results by anonymized IPs vs normal ones.

Also it depends what you are comparing to locate?
- country
- region
- city

In things of countrys its mostly the same result (unless you live at the border)
But when it comes to citys (specially on rural areas) it can cause a difference of about 250km.
To get this you have to understand how IPs are "working" in the background. IP ranges are getting defined for some areas. (say its fixed to a area where 20.000 people live, so you know if a IP range is defined it have to be anywhere there)
In towns this areas are very limited due to so many people at one place. In rural areas this is not the case.
So with the same IP (same untill the last block) you could be where you are or somewhere 200km away from your place, due to so less people on rural areas.

Hope I could explain it a bit. But IP-Ranges are reserved and they will not change in future a lot.

I will give you here some articles to have a read.

(1): https://brianclifton.com/blog/2018/06/19/impact-of-anonymizeip/
(2): https://www.conversionworks.co.uk/blog/2017/05/19/anonymize-ip-geo-impact-test/
(2.1): https://www.conversionworks.co.uk/wp-content/uploads/2017/05/1-1024x731.png (Image)
(3): https://www.gosquared.com/support/articles/1805590-can-i-anonymise-ip-addresses-when-tracking-
(4): https://matomo.org/blog/2018/04/how-to-not-process-any-personal-data-with-matomo-and-what-it-means-for-you/ (Topic "**6. Location**")

**Comment by acelaya** [comment]
> Do you mean a "Warning" to the Link caller oder "user" like the installer/admin?

I mean a warning for the admin while installing shlink. For end users this would be transparent.

Thanks for all the information. I will take a look at those articles.

The fact that geolocation is done on the anonimized address is due to historical reasons.

In the past, shlink used to use a system slower than GeoLite, therefore, geolocation had to be done asynchronously (to avoid delaying end users to be redirected).

That meant that the IP address was stored, and later processed and geolocated.

Later, the GDPR appeared, and I had to change shlink so that addresses were anonimized.

That, together with the existing approach, made geolocation happen on the anonimized address.

That said, considering that GeoLite is reasonably fast, I could change the architecture a bit so that geolocation happens on the real address and then the anonimized one is stored (unless you configured shlink to store full addresses as discussed before).

That should give a more accurate geolocation.

**Comment by acelaya** [comment]
Hey @MartinH0 

I have started to work on this (#642) and I have realized there is a small problem with it. Let me elaborate:

There's currently two ways to do IP address geolocation:

* When serving Shlink with swoole, an async event listener is registered which is triggered when a short URL is visited, but it's executed right after the user has been redirected to the long URL.
* When serving Shlink with a regular web server, there's a CLI command that you are responsible to schedule.

In the first approach it is possible to pass the real IP address (non-anonymized) as part of the event's metadata.

In the second one the location happens based on what has been stored in the database, which is the anonymized address.

My intention was to make the async event listener from the first approach to be syncronous and be used both for swoole and non-swoole setups, as GeoLite is reasonably fast.

However, as both the CLI command and the listener were designed to be run asynchronously (as in, not blocking end-user requests), both of them are doing two things.

* They locate visits -> reasonably fast
* They download/update the GeoLite database when needed -> not fast at all.

Because of this, I cannot follow the approach I had in mind.

I will probably have to do a deeper architectural change, making the listener only geolocate visits, and moving the database file handling somewhere else, but that's a way deeper change than expected, so I will have to move this to another release.

In the short term, you can migrating to swoole, as it has many other benefits, and next release will include geolocation on the real IP address when using swoole.

**Comment by acelaya** [comment]
Hey @MartinH0!

Shlink v2.2.0 will have this during installation/update:

![image](https://user-images.githubusercontent.com/2719332/81411780-2488c180-9143-11ea-87d1-3dd43a6856f8.png)

The installer will require a double confirmation and display a warning in case you try to disable the IP anonymization.

An env var will be also provided for the docker image, `ANONYMIZE_REMOTE_ADDR=false`.
