### ISSUE TITLE
Not all referrer are detected.

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#649]
#### How Shlink is set-up

* Shlink Version: 2.0.4
* PHP Version: 7.4.2
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB

#### Summary

I pasted soem Links from Shlink to Instagram and when they get clicked they do not show the referrer is Instagram but Instagram does clearly open them in a new Tab with a "redirect" from Instagram. All other Services GA (Google Analytics) can detect that the call is coming from Instagram but Shlink somehow cant.

**Comment by acelaya** [comment]
The logic to determine the referrer was implemented quite some time ago and it's pretty basic, so it's probably missing some use case. I'll expend some time investigating that.

Alternatively, it could also be related with some proxy in front of shlink which is not properly forwarding the referrer, but I don't think it's that on your case.

**Comment by acelaya** [comment]
Hey @MartinH0 

Can you confirm if you are using https with your shlink host?

Also, if there's any chance that you can share some instagram post in which you have shared Shlink short URLs, that would also help me figure this out.

**Comment by MartinH0** [comment]
Yes I can confirm I'm using HTTPS at all of my domains and subdomains.

Sorry I was not talking about a post but about posting them in Instagram (sending them in PM) so I send one in Chat.
After that the Link got clicked and was located right, but no referrer was shown.

**Comment by acelaya** [comment]
Ok, got it. I will try to reproduce it.

**Comment by acelaya** [comment]
I have another question @MartinH0 

Have you experienced the referrer to be missing in all cases, or for other cases shlink is properly showing the referrer?

**Comment by MartinH0** [comment]
For other cases I did not notice any wrong/false detecting of the referrer or any loss of detection.
But I think at messengers its becasue of the Link gets opened with a "redirect" from the App itself like in Instagram (or Google if you send it via Mail) so therefor it is not recognizing it.

Maybe it does even open the Link in a "**noreferrer** noopener nofloow" link or something like this?
Dont know if its even possible to identify the referrer then.

I just tested it again and send me my own shlink in Instagram

This is what happened.

Before I even clicked the Link it got called 3 times (from Instagram) and when I click it it does get show a referrer as "l.instagram.com" but I think thats because its a trusted Link for me (as its from myself

I will do some further testing but sometimes its not recognizing it at all.

**Comment by acelaya** [comment]
Thanks @MartinH0. That was really helpful.

What I have managed to find is that, if you have any URL posted on instagram, they actually always forward it first to l.instagram.com.

Apparently they do that precisely to be able to mask the referer, so that destination sites never know from what post/profile/place the link is actually coming from. The only thing the site will know is that the request is coming from l.instagram.com.

Gmail/google, facebook, linkedin, etc. have similar approaches.

Another thing that I have found during my investigation is that the browsers never send the Referer header when going from an https to an http page. They do it on any other combination though. However, this shouldn't be the problem in this case, but I'll probably document it in order to encourage people to use https with shlink.

So, in order to do a real test, I posted a locally-hosted shlink URL on instagram, as you can see here.

![image](https://user-images.githubusercontent.com/2719332/74106063-b17fa700-4b63-11ea-83fa-2319a75de32c.png)

However, if you check where the URL is actually pointing, it's this:

![image](https://user-images.githubusercontent.com/2719332/74106079-d7a54700-4b63-11ea-9e82-ac074908b17b.png)

So, you were right on the fact the URL is not sending the referer there, but it doesn't matter, as the request to Shlink will be performed from l.instagram.com anyway.

The next thing I did was visiting the link, and all the times Shlink received the Referer, with l.instagram.com on it (which was expected).

![image](https://user-images.githubusercontent.com/2719332/74106110-07ece580-4b64-11ea-9bd6-06f26eb649a0.png)

So, I'm not being able to reproduce a case in which no referer is receibed by Shlink.

The thing is that the Referer is actually a header the http client (in this case, the browser) can decide to send or not send. Maybe there are other use cases that can disable that (like certain security configs on the browser, plugins, ad-blockers or the incognito mode).

So taking all of that in mind, I will leave the issue out of v2.0.5 for now, and waiting for further investigation on the subject.

**Comment by MartinH0** [comment]
Could I add here that I added one link to my website the a Tag is this (censored):

`<a href="https://l.domain.tld/GPSI-SOMETHING" target="_blank" title="GPSI"><span >GPSI</span></a>`

But somehow again the referrer (my website) is not detected.
Is there anything I have to configure on my website and the problem is based on my website or how can I make my website being added/detected as referrer?

**Comment by acelaya** [comment]
It's most probably because of the `target=_blank`.

As far as I can see, most recent browsers do not pass the referrer in that case.
