### ISSUE TITLE
Make sure default domain is stripped out when creating new short URLs

### ISSUE THREAD

**Issue by alkin** [shlinkio/shlink#650]
Hi

I am trying to get the longUrl from the rest api and keep getting an error saying that the short code was not found.

```
>>> Shlink::shorten('http://www.peepi.com.br');
=> "http://peepi.xyz/1dJp2"

>>> Shlink::GET('/short-urls/1dJp2');
=> [
     "shortCode" => "1dJp2",
     "title" => "Short URL not found",
     "type" => "INVALID_SHORTCODE",
     "status" => 404,
     "detail" => "No URL found with short code "1dJp2"",
   ]
```

I checked the database and the short url was indeed created.

![image](https://user-images.githubusercontent.com/131324/74045977-7a1aca00-49ac-11ea-95f7-0a0e2036af47.png)

```
>>> Shlink::GET('/short-urls');
=> [
     "shortUrls" => [
       "data" => [
         [
           "shortCode" => "1dJp2",
           "shortUrl" => "http://peepi.xyz/1dJp2",
           "longUrl" => "http://www.peepi.com.br",
           "dateCreated" => "2020-02-07T16:16:20+00:00",
           "visitsCount" => 0,
           "tags" => [],
           "meta" => [
             "validSince" => null,
             "validUntil" => null,
             "maxVisits" => null,
           ],
           "domain" => "peepi.xyz",
         ],
       ],
     ],
   ]
```

The link also works as expected

```
> wget http://peepi.xyz/1dJp2                                                                                                                                              
--2020-02-07 13:24:19--  http://peepi.xyz/1dJp2
HTTP request sent, awaiting response... 302 Found
Location: http://www.peepi.com.br [following]
```

I also tried using the `domain` query parameter with no success.

I am using an external MySQL as database.

Am i missing something or is this a bug ?

**Comment by alkin** [comment]
I am using MySQL v8 by the way

**Comment by alkin** [comment]
It also affects CLI:

![image](https://user-images.githubusercontent.com/131324/74048040-31fda680-49b0-11ea-85c0-dff1ee6aa36d.png)

**Comment by acelaya** [comment]
According to the screenshot, it looks like the short URL was created with a domain attached to it.

You usually either create short URLs for the default domain (by not providing any value, in which case domain_id would be null), or you create it by a non-default domain, in which case, you also need to provide the domain when searching for it. In this case it would be `/short-urls/1dJp2?domain=peepi.xyz`.

The only problem I can see here is that, if peepi.xyz is also your default domain, it should have been stripped out when created, making the domain_id to be null, and that, I would consider it a bug (in fact, providing the default domain in the query won't make a difference, since shlink converts the default one to null and it will still not be found).

Can you confirm if that's the case?

**Comment by acelaya** [comment]
So, long story short, if you plan to use just one domain, as a temporary workaround, avoid sending that domain when creating new URLs.

For the existing one, you can fix it by manually setting the domain_id to null in the database.

**Comment by alkin** [comment]
You are right. The default domain was "peepi.xyz" and it was also passed during the creation of the short link. I solved the issue by not passing the domain.

**Comment by alkin** [comment]
![image](https://user-images.githubusercontent.com/131324/74058145-274d0c80-49c4-11ea-90a5-b941b6954242.png)

**Comment by acelaya** [comment]
I'm glad that it's working now.

**Comment by acelaya** [comment]
Hey @alkin 

I have just merged the fix that will make sure Shlink ignores the default domain even if it is provided when creating a short URL.
