### ISSUE TITLE
Could add same ShortLink with same targetlink twice

### ISSUE THREAD

**Issue by MartinH0** [shlinkio/shlink#661]
#### How Shlink is set-up

* Shlink Version: 2.0.4
* PHP Version: 7.4.2
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB
#### Summary
![Shlink double Link](https://user-images.githubusercontent.com/17692860/74821789-6ce2d100-5304-11ea-9f2b-a9a52a564108.PNG)

I was just clicking "Create" twice and no error occured, after added the Link I wanted to add a Tag and saw it does exist twice.
I then delted one (and both got deleted) but before I refreshed to make sure the System does really contain this link twice and this is not just some client side bug if clicked twice.
After reloading it again showed both.

This is where I made the Screenshot.

In my eyes, the same Shortlink should never exist twice.

**Comment by acelaya** [comment]
Yep, it should not be possible to create the same short link for the same domain twice.

When a custom slug is provided, the second time it should fail.

I will investigate what happened.

Regarding you not being able to delete one of them afterwards, that could be related with a bug on the web-client that was recently fixed, but it could also be because it was duplicated while it shouldn't. I will investigate.

**Comment by MartinH0** [comment]
I could delete one. But the other also got deleted aswell in the same process.
For me this also makes sense, as I had to confirm the slug.
Then the Link with the Slug got deleted (but as both have the same slug both got deleted)

Does this makes sense?

Also a Serverside validation would be good, otherwise its modifyable. So I think this should not be checked at the web-client.

I will update both to its latest version and report back the next days.

Thanks for the fast response!

**Comment by acelaya** [comment]
Hey!

I have just checked and it didn't let me create the same twice (I received an error the second time).

I think that in your case, it might be caused by a combination of bugs already fixed on latest patches from shlink and shlink-web-client.

Could you try updating to shlink 2.0.5 and shlink-web-client 2.3.1?

If you use app.shlink.io, then you are already on latest one, but an old one could be cached.

**Comment by acelaya** [comment]
I have rechecked and there's a unique index at DB level for the short_code (or slug) and domain combination, so it's not possible to create the same short URL twice.

However, before v2.3.1, the web client had several issues related with multidomain. Those could be perfectly causing everything.

**Comment by MartinH0** [comment]
I could even not reproduct it myself..
I just know I still have the same setup like then when it happened, but internetconnection was not good. Will do some more tests before updating and reporting back when I know what it was causing.

**Comment by acelaya** [comment]
Awesome. It would be nice to find out what's the root cause before jumping into conclusions.

I also considered that it could have been produced by a race condition, in which two links were created simultaneously. That would mean locks are not properly setup.

Also, the creation form in shlink-web-client should be disabled while creating a link. If it's not, I will fix it, as it would mitigate this kind of issues.

**Comment by MartinH0** [comment]
Could not reproduce this issue in any other testscenario. Still dont know why or how this could happen.

I will close this issue for not bloating the issue section. If I find out anything new about this issue I will reopen it.

**Comment by acelaya** [comment]
Thanks for checking again.

I will also do some tests as soon as I have some time, to make sure it's not due to some race condition.
