### ISSUE TITLE
Setting default_short_codes_length has no effect

### ISSUE THREAD

**Issue by jpatters** [shlinkio/shlink#667]
#### How Shlink is set-up

* Shlink Version: 2.0.5
* How do you serve Shlink: Docker image
* Database engine used: PostgreSQL

#### Summary

Setting `default_short_codes_length` has no effect. The short code length is always 5

#### Current behavior

The short code length is always 5

#### Expected behavior

If I set `default_short_codes_length` to 7, I expect the short code length to be 7.

#### How to reproduce

Set `default_short_codes_length` to something other than 5.

I've noticed that `DEFAULT_SHORT_CODES_LENGTH` is hard coded to 5 here: https://github.com/jpatters/shlink/blob/fix/default_short_codes_length/module/Core/functions/functions.php#L13. I'm not sure if that is what is causing the issue but it's the only potential thing I can find.

**Comment by acelaya** [comment]
Sorry @jpatters, this is caused by a bad decision of merging documentation for a feature which is not yet released.

Customizing the short code length will be possible starting with v2.1, but you can also use the `latest` docker image which already includes it.

Sorry for the inconveniences. I will try to update the docs.

**Comment by jpatters** [comment]
Ah. Ok. Thanks.
