### ISSUE TITLE
Can i upgrade shlink from v1.16.2 to latest version with one step ?

### ISSUE THREAD

**Issue by renaldiAlterra** [shlinkio/shlink#710]
#### How Shlink is set-up

* Shlink Version: 1.16.2
* PHP Version: 7.2.19
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB (10.1.38)

#### Summary

Your works is absolutely Wonderful, Thanks for it

I want to ask, it is possible to me..for update it to the latest version through ? 2.1.2 if i'm not mistaken right ?

do i have yo upgrade my php version to 7.4 also ?

and all of my shortlink not disappear right ? or there is another way to export and backup the short url we already made from old version oh shlink to import it on the newest or updated one ? (when if we're facing an issue when upgrading ? )

Thanks before 😄🙏

**Comment by acelaya** [comment]
Hello @renaldiAlterra 

In theory yes. I have just created a clean installation with v1.16.2, then created a few short URLs, visited some of them, created some tags, etc.

Then, I downloaded a dist file for v2.1.2, run the update script, pointing to previous folder, and it imported everything properly. Then, I run this version, and everything was still there. No data lost.

**However**, you are making a big jump, and maybe you have something I missed in my test, so I would recommend you follow these steps:

* First, read the upgrade guide, and make sure you don't have a hard dependency on any of the things that have been removed or changed. You can find it [here](https://github.com/shlinkio/shlink/blob/develop/UPGRADE.md#from-v1x-to-v2x). The main consideration is that Shlink 2.x requires PHP 7.4, so make sure you have it.
* Then, stop your instance, so that it does not receive any visit while you are performing the update, ensure data consistency during the mgration.
* Then, create a backup of your database. If something goes wrong during the process, you will at least be able to go back to v1.16.2 without loosing your data.
* Finally, download the latest dist file and run the upgrade as explained [here](https://github.com/shlinkio/shlink#update-to-new-version).

If everything goes ok, make Shlink available again and do some tests to make sure it works.

**Comment by renaldiAlterra** [comment]
thanks for your simulate on it..

but i simulate on it too (at the first place i can't install it anymore v1.16.2, then i found to have change geolite url.. thanks to you too that provide the url also in this repo issue also😄)

so i make the same env as same as possible..

php7.2 -> i upgrade it to php7.4
mariadb 10.1.44

i create some link, visit it..

before upgrade, i turn off the nginx and dumpmysql

then i run bin/update.. but i got error like this..

![image](https://user-images.githubusercontent.com/49466271/78581670-61207f00-785e-11ea-9c61-cf63b3cade7a.png)

what sould i do ? 

upgrade the mariadb ? im using debian 9 ..
it seems the latest version on it..

oh yes, can i have imported data from my old server ?

just in case i create new server with debian 10 ..

Thanks before..🙏

**Comment by renaldiAlterra** [comment]
sorry for bothering, i solved this with update mariadb to 10.2 from 10.1

and i done the upgrade from 1.16.2 to 2.1.2

Big Thanks 🙏😄

**Comment by acelaya** [comment]
Amazing, I'm glad to hear that.

I didn't have the chance to investigate the index issue, so I'm glad that you manage to sort it out.

**Comment by renaldiAlterra** [comment]
Sure, oh can i ask one more question ? or i need to create new issue ?

it's that safe for me to delete the old folder of shlink ?
cause i copy the path of it when upgrading

**Comment by acelaya** [comment]
Yes, once updated, you can delete the old one.

**Comment by renaldiAlterra** [comment]
Thanks
