### ISSUE TITLE
Edit long URL after shrinking

### ISSUE THREAD

**Issue by MatthiasDunker** [shlinkio/shlink#718]
#### Summary

Hey,

it would be great to being able to edit the long url after generating the shlink.
A simple case would be a typo in the long url, but the shlink would have already been spread.
Another case would be a kind of history last function. One shlink would always point to a current target. Like first to a registration form of an event, after the registration period the author would change the long url to the program and after a while to a recap or instagram channel.
Yet another case could be a printed magazine, which has to be printed soon, but the long urls are not yet known. A shlink and its qr code could get printed and the long urls would get filled in or corrected right before the magazines release.

What do you think?
Would be eager to help if possible.

**Comment by acelaya** [comment]
Editing short URLs is already possible since v2.1. See https://github.com/shlinkio/shlink/issues/521

The integration has also been implemented on shlink-web-client and will be part of the upcoming v2.4, which will be released in 1-2 weeks. See https://github.com/shlinkio/shlink-web-client/issues/235

**Comment by MatthiasDunker** [comment]
Thanks @acelaya
My bad! Thanks for your work

**Comment by acelaya** [comment]
No worries 🙂
