### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by muvmag** [shlinkio/shlink#747]
#### How Shlink is set-up

* Shlink Version: x.y.z
* PHP Version: x.y.z
* How do you serve Shlink: Self-hosted Apache|Self-hosted nginx|Self-hosted swoole|Docker image
* Database engine used: MySQL|MariaDB|PostgreSQL|MicrosoftSQL|SQLite (x.y.z)

#### Summary

I am unable to connect to the app and continue to get a message saying it cannot connect to this Shlink server, albeit seemingly having the configuration correct (I could be wrong though), and it also doesn't seem to be connecting to the domain.

Do you have any suggestions on where to begin? Any help would be immensely appreciated!

**Comment by acelaya** [comment]
Could you give me some more details? Like, filling the "How Shlink is set-up" info would be a good start.

Other than that, how are you accessing your shlink instance? Are you using shlink-web-client? If that's the case, is it a self hosted instance?

Have you tried just opening the root short domain you are using to serve shlink? Does it show a 404 page?

And finally, could you check the logs? The way to check those is different depending on how you are serving Shlink, so I first need the "how shlink is set-up" info in order to better guide you on this point.

**Comment by muvmag** [comment]
Installed on a DO droplet, and accessed by the web-client. It's hosted alongside a WP installation (which takes you to that website), but the short domain isn't directed anywhere, except as the shlink short domain currently, so nothing shows up.

**Comment by acelaya** [comment]
You need to configure the short domain in your DNS to point to the droplet's public IP.

**Comment by muvmag** [comment]
I was incorrect, it was already pointed at the droplet.

**Comment by acelaya** [comment]
Then we are back at this point:

> Have you tried just opening the root short domain you are using to serve shlink? Does it show a 404 page?
> 
> And finally, could you check the logs? The way to check those is different depending on how you are serving Shlink, so I first need the "how shlink is set-up" info in order to better guide you on this point.

**Comment by acelaya** [comment]
Closing this for now.

@muvmag let me know if there's any other way I can help.
