### ISSUE TITLE
PDOException - Queries not buffered by default

### ISSUE THREAD

**Issue by jmadureira** [shlinkio/shlink#750]
#### How Shlink is set-up

* Shlink Version: 1.21.2
* How do you serve Shlink: Docker image
* Database engine used: MariaDB (10.2.21)

#### Summary

Got the following error white trying to create short URLs concurrently:

`PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /etc/shlink/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121`

I noticed that query buffering has been added to shlink on `v2.2.0-alpha.1` at `/docker/config/shlink_in_docker.local.php` which ought to fix this issue. Is it possible to include this change on the 1.21 banch as well?

#### Expected behavior

No errors should the logged

#### How to reproduce

Configure webhooks to receive notifications every time a link is clicked.

Make concurrent requests to both create short urls and visit links.

**Comment by acelaya** [comment]
Hey @jmadureira 

Yes, that's a weird bug that has been recently fixed. Actually it's not really part of v2.2.0-alpha.1, as I thought I had it fixed just to later find out the issue was still there and the fix was different.

The fix is actually this: https://github.com/shlinkio/shlink/commit/56932e4ea6904c5acfe3f77387ddef97e181ba6a

I also cannot backport it, as v1.x is no longer maintained. I might consider providing fixes for high-severity security issues, but that's all.

However, there's an easy way for you to workaround this issue.

The docker image allows you to pass a configuration file that gets merged with the app config: https://shlink.io/documentation/install-docker-image/#provide-config-via-volumes

Some common configuration is documented there, but you can virtually overwrite any configuration value using this approach.

If you provide a config file with this content, you will be overwriting the malfunctioning config param:

```json
{
  "mezzio-swoole": {
    "enable_coroutine": false
  }
}
```

Let me know if that helped.

**Comment by acelaya** [comment]
Sorry, my bad. I have just realized v1.X was still using the old Zend components, so the main key it would not be `mezzio-swoole` but `zend-expressive-swoole` instead.

I have edited the comment.

**Comment by jmadureira** [comment]
Hello @acelaya 

Thanks for the reply.

I'll have some work to do then. I'll be closing this issue since the target version is no longer maintained.
