### ISSUE TITLE
500 error on dates

### ISSUE THREAD

**Issue by DreamplaySE** [shlinkio/shlink#764]
#### How Shlink is set-up

* Shlink Version: 2.2.0
* PHP Version: 7.4
* How do you serve Shlink: Self-hosted nginx
* Database engine used: MariaDB

#### Summary

When trying to send "validUntil" or any other date in the body I get a 500 server error and [this error in the log](https://pastebin.com/kEhYZbYB). Tried both "2020-05-13T00:07:19Z" or "2020-05-13T00:07:19+00:00". Including milliseconds creates returned 400 INVALID_ARGUMENT error type. What am I doing wrong? Is this a bug?

**Comment by acelaya** [comment]
Hey @DreamplaySE.

Yes, it looks like a bug. It seems like it happens when you create a short URL without `validSince`, and then try to create another one where:

* All the params match the previous URL, except that this time you send the `validSince` and/or `validUntil` params.
* You send `findIfExists=true`.

When this happens, Shlink tries to match the `validSince` and/or `validUntil` dates, but since it's null in the first one, it throws this error.

Can you confirm if this is your use case?

**Comment by DreamplaySE** [comment]
Yes it's exactly my use case. My apologies for not understanding the error myself, found it quite late yesterday and don't really know php. Thank you for keeping this project running generally it's been amazing.

**Comment by acelaya** [comment]
Don't worry. It's not your job to understand the error.

You provided all the information needed for me to quickly find out what was wrong, and I appreciate that.

**Comment by acelaya** [comment]
Hey @DreamplaySE.

I have just released Shlink v2.2.1, which fixes this issue https://github.com/shlinkio/shlink/releases/tag/v2.2.1
