### ISSUE TITLE
Make Shlink available in the AUR

### ISSUE THREAD

**Issue by AlphaJack** [shlinkio/shlink#775]
#### Summary
I was wondering if you could port Shlink to the AUR.
The manual installation is extremely easy (just unzip and setup the reverse proxy), but in this way users get notified about new releases and can update the package even more easily.  
Helpful resources may be the [AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines) and the [`yourls` PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yourls) as example.  
I can test the PKGBUILD in my system if you need some help

Not related, but thank you for your hard work, I noticed huge speed improvements by updating from v1 to v2

**Comment by acelaya** [comment]
Thanks for the kind words @AlphaJack :slightly_smiling_face: 

Regarding AUR support, I see it a bit too specific to one distribution so that it really makes sense to maintain it.

I definitely want to find a way to improve the installation and update, but I would like to find a more generic way to do it.

**Comment by AlphaJack** [comment]
Can you point out to me what files should the package manager ignore while installing? For example `yourls` has [Includes/Config/Config.php](https://github.com/YOURLS/YOURLS/blob/master/includes/Config/Config.php): this file is moved to `/etc/webapps/yourls/config.php` and symlinked to `/usr/share/webapps/yourls/Includes/Config/Config.php` (where the rest of the package is installed).  
The file `/etc/webapps/yourls/config.php` is set to not be overwritten when updating the package.

**Comment by acelaya** [comment]
I guess the equivalent would be the `config/params/generated_config.php` file, which has the customized options.

However, this file is not part of shlink when you download it for the first time, but generated by the install CLI tool.

**Comment by AlphaJack** [comment]
> Recursively grant write permissions to the `data` directory. 

What other folders does the shlink user need to write to? I see that`config` is required to generate the configuration file

**Comment by acelaya** [comment]
That is because when serving the app with nginx/apache, the system user is usually different than the one owning the files, which could make logs and other assets generated at runtime fail. Those will always be generated inside the data directory.

On the other hand, the installation tool is usually run by the system user owning the files, so it should be ok. If that is not the case, then you would also need to grant writer permissions for the config/params folder.

**Comment by AlphaJack** [comment]
@acelaya I've just published it here: https://aur.archlinux.org/packages/shlink/
