### ISSUE TITLE
Increase the number of followed redirects

### ISSUE THREAD

**Issue by ToeiRei** [shlinkio/shlink#79]
For example a site redirects from http:// to https:// the link is considered as invalid instead of following the redirect and snatching the correct link

**Comment by acelaya** [comment]
I have been playing with this, and I can't reproduce it.
In fact, the HTTP client that's being used by shlink, automatically follows redirects, with a maximum number of 5. Maybe you are trying to follow more than 5 redirects, which results in an error and shlink will consider it an invalid URL.
That is to say, there is nothing to fix as long as there are 5 redirects to follow or less. In those cases, the short URL is properly created.

However, I've found something that could not be very intuitive.
Let's get this example.
My website is https://www.alejandrocelaya.com, but both http://alejandrocelaya.com and https://alejandrocelaya.com, redirect to the first one.
If you create those three URLs in shlink, it will work, but they will be considered different URLs. I'm not sure if that should be the behavior, because that makes stats to be split, while the user is ending in the same page.
Maybe shlink should follow redirects and perform the existance check with the final URL.

What do you think?

**Comment by acelaya** [comment]
I have just checked, and Google's URL shortener seems to consider them different URLs, so it behaves the same way as shlink right now.

**Comment by acelaya** [comment]
I'm increasing the number of followed redirects by now, and I'll create a new iccue to consider changin the behavior
