### ISSUE TITLE
Need help with serving Shlink by "classic web server"

### ISSUE THREAD

**Issue by Bogey** [shlinkio/shlink#806]
#### How Shlink is set-up

* Shlink Version: Latest
* PHP Version: 7.4.4
* How do you serve Shlink: Self-hosted Apache
* Database engine used:MariaDB

#### Summary

I followed the documentation and everything went well up to API generation.
Then  I come to a complete halt when it comes to connecting the web client ... 

Thanks for your assistance,
Erwin

**Comment by acelaya** [comment]
Can you please check the logs? They are stored inside the data/log folder. There should be one file per day.

Also, how are you trying to consume the API? Are you using shlink-web-client? If so, can you check exactly what's the request failing? You should be able to see it by opening the "requests" tab in the browser's console.

**Comment by Bogey** [comment]
I'm using indeed shlink-web-client. I can add a server, but that's about it. I then end up with "Oops! This is awkward :S"

The log doesn't say much:
[2020-07-08T23:05:39.680331+02:00] [NULL] Shlink.INFO - Successfully acquired the "db:create" lock.
[2020-07-08T23:05:39.681012+02:00] [NULL] Shlink.INFO - Expiration defined for "db:create" lock for "90" seconds.
[2020-07-08T23:05:39.898063+02:00] [NULL] Shlink.INFO - Successfully acquired the "db:migrate" lock.
[2020-07-08T23:05:39.898657+02:00] [NULL] Shlink.INFO - Expiration defined for "db:migrate" lock for "90" seconds.

**Comment by acelaya** [comment]
I think your shlink instance is not receiving requests, which makes me think the browser is blocking them.

Are you using https on your shlink instance? If not, since app.shlink.io uses it, most modern browsers block requests to non-https sites. You need to manually allow it.

https://github.com/shlinkio/shlink/issues/766#issuecomment-628066915

**Comment by Bogey** [comment]
I used both your app.slink.io and the install webclient. I tried it with Chrome, Firefox and Safari. Everytime I get a "Oops!"
Would you mind taking a look 'under the hood', see if everything is setup as it's supposed to be?

**Comment by acelaya** [comment]
I'm afraid I don't provide that kind of support.

I would try these two things next:

* Try just opening your shlink URL on a browser. If everything is properly configured, you should see a "not found" page.
* Open the browser console to see exactly what kind of error are you getting, in order to know if it's just a misconfiguration, or maybe the browser is not reaching your shlink instance for any reason.

**Comment by Bogey** [comment]
I think the documentation needs some specifics. If you want your project to be a success, then it should be clear how to install it. I've run out of options. You still can take a look if you want, I'll let it sit for 48h and then it's sayonara Shlink.
:(

**Comment by acelaya** [comment]
I understand it's frustrating when trying to use some tool and not being able to get it working. There's of course room for improvement in the docs. For example, I'm planning to add a troubleshooting section with common issues that some users have reported more than once.

However, the thousands of working installations tell that it is not that bad.

This is a project you can use for free, and I maintain it in my own free time. I'm not charging you anything for the tool, and I'm also spending time trying to help you.

However, you have refused to try some of the things I told you, and you are now being rude.

Because of that, I'm closing this issue. If you decide to come back with a different attitude, I will be glad to reopen it and continue helping you.

**Comment by Bogey** [comment]
You are absolutely right that there’s some time involved to get things working. I also appreciate the fact that it’s free and you’re running this in your spare time. I love the main website and the screen shots, that’s why I really want to get it working.
I didn’t refuse anything you suggested, I did them. I can can show you the conversation I had with my webhost, because we did a lot more.
What I cannot understand is that your idea of support on a project, that clearly was made with a lot of dedication and devotion, is a few vague hints and then telling me I’m rude...
I wish you all the best with Shlink and perhaps I‘ll give it another go when I’m using a VPS, but for now I’m sticking with YOURLS.

**Comment by garethjax** [comment]
@acelaya hello! Sorry if i reopen the thread, but i'm having the same issue.

My OS is OSX Mojave, but i've tried with a couple of different browser and the result is the same.

As context, i've installed the script successfully on a "provisional" subdomain based on [opalstack](https://www.opalstack.com) (a spin-off of webfaction, a shared hosting for developers).

![not found message, as expected](https://user-images.githubusercontent.com/3459602/102022693-c97a1580-3d88-11eb-95a9-04cbb47b3c43.png)

Inside the sever log there are the same lines mentioned above, while i've checked the chrome console and i've discovered those errors:

![image](https://user-images.githubusercontent.com/3459602/102022721-f5959680-3d88-11eb-83df-c8c74ad3531d.png)

This could be a problem, the provisional domain you see in the error don't have an SSL certificate, so it answers only to the HTTP request.

I'm registering a new domain to obtain a certificate from let's encrypt and i'll recheck the connection.

I'll post an update when i have more data!

**Comment by garethjax** [comment]
**Update**: after the certificate has been issues and i was able to route all the request on the https protocol, everything started working perfectly.

So, it seem that having https enabled on the target domain, is mandatory for the react web client!

**Comment by acelaya** [comment]
This limitation comes from latest versions of Google chrome only, it's not something enforced by shlink-web-client.

**Comment by garethjax** [comment]
Ah interesting! It's worth mentioning in the documentation since chrome is the browser with the largest share!

**Comment by acelaya** [comment]
Yep, that's why I added the "troubleshooting" tag 🙂
