### ISSUE TITLE
location address    added question mark   

### ISSUE THREAD

**Issue by xjdata** [shlinkio/shlink#807]
#### How Shlink is set-up
* Shlink 2.1.4
* How do you serve Shlink: Docker image
* docker image  shlinkio/shlink latest 2e3ce0d4ccff 8 days ago 205MB
* Database engine used: MariaDB   Docker image   mariadb 10.3.2 d883b65ef604 2 years ago 397MB

#### Summary

location address    added question mark   

#### Current behavior

long url is  `http://imxin.cn/5`   this is test url  it's   Unreachable

![image](https://user-images.githubusercontent.com/4524983/87111347-b9bb4a00-c29b-11ea-89e6-5482ba64f498.png)

Short URL is   `http://2jq.cn/ZOX9d`

![image](https://user-images.githubusercontent.com/4524983/87111724-a0ff6400-c29c-11ea-962a-3db0e6c29347.png)

Location: http://imxin.cn/5?

#### Expected behavior

Location: http://imxin.cn/5    

Jump  to  longUrl   do not add  question mark

**Comment by acelaya** [comment]
Shlink forwards the query from the short URL to the long one. However, here is like it is detecting an "empty" query which is making the question mark being appended with nothing else after it.

Is this happening for you on every short URL, or only this particular one?

**Comment by xjdata** [comment]
yes  every short URL

![image](https://user-images.githubusercontent.com/4524983/87145201-88fb0500-c2db-11ea-93a5-8ab2197bc01c.png)

**Comment by acelaya** [comment]
Ok, then it may be a general issue. In most cases, everything should work anyways, so it could have passed unnoticed up until now.

I will do some checks later and try to get it fixed.

**Comment by acelaya** [comment]
Hey @xjdata, I have managed to reproduce the issue.

It is caused by a new library introduced 2 weeks ago here https://github.com/shlinkio/shlink/pull/797/files#diff-4a1ed4e0e5ea390d8945fb464226a3dbR70, when adding support for deeplinks and URIs with a schema othe rthan http and https.

This library appends the `?` when calling `->withQuery(...)` and passing an empty string, while the old one properly detected the empty string. It's easy to fix.

The good thing is that no stable versions are affected, just develop. You can solve the problem by downgrading to docker's `2.2.2` or `stable` tags.

**Comment by acelaya** [comment]
In any case, I have just merged the fix and it should be available in `latest` docker tag as soon as this build finishes: https://travis-ci.org/github/shlinkio/shlink/jobs/707036655

**Comment by xjdata** [comment]
👍   thank you
