### ISSUE TITLE
How to install in "public only" directory?

### ISSUE THREAD

**Issue by pembo13** [shlinkio/shlink#839]
#### How Shlink is set-up

* Shlink Version: 2.3.0
* PHP Version: 7.4
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MySQL

#### Summary

Instructions don't give any hints for installing in a "public only" on shared host type environment where all the files would be placed in a public DOCUMENT_ROOT. The docs assume that the project path would be one level above the DOCUMENT_ROOT which points to the "public" directory. In a hosting environment without full access to Apache configs and system directories, current documentation instructions don't apply.

See WordPress, phpMyAdmin as alternate examples.

**Comment by acelaya** [comment]
Hey @pembo13 

Shared hostings have never really been shlink's target, since there are other popular projects already covering that field.

Instead, the project is focused on a bit more advanced infrastructures, where at least you work with a private server.

Because of that, most of the code is hidden safely out of the document root, as otherwise, it presents some potential security fail points (I know WordPress and many others do it, but that doesn't make it right).

That said, I would say it should be possible to workaround this somehow.

Can I ask what shared hosting are you using?

**Comment by pembo13** [comment]
@acelaya I'm using WebFaction

**Comment by pembo13** [comment]
@acelaya I was able to get things to work by copying the contents of "public", and adding a .htaccess with `Deny from all` to each folder.

**Comment by acelaya** [comment]
The first thing I would try is connecting via SSH to your server (you will need this anyway to run shlink installation tool), and see if you can cd into document root's parent directory.

https://docs.webfaction.com/user-guide/access.html#connecting-with-ssh

In all shared hostings I have used in the past, SSH actually allowed you to go one level higher, even though via FTP it looked like you only had access to the document root.

If it works, then you can upload your files via SFTP (which is FTP over SSH), using the same SSH credentials.

**Comment by acelaya** [comment]
> @acelaya I was able to get things to work by copying the contents of "public", and adding a .htaccess with `Deny from all` to each folder.

Nice. That was going to be my next suggestion :)

Glad to see it worked. I'll probably try to document this.

**Comment by pembo13** [comment]
@acelaya great.
