### ISSUE TITLE
Editable OG open graph link previews

### ISSUE THREAD

**Issue by thehateguest** [shlinkio/shlink#848]
It would be amazing being able to add and edit link preview - and being able to change the image (and maybe the texts) shown by social network platforms when the link is shared there. 

Please let me know if I can help in any way, I am not a coder but would love to see this implemented.

**Comment by acelaya** [comment]
Hey!

This is definitely something nice to have. However, there are a lot of considerations that make it hard to implement.

* The OG standard is quite different for every social network, which is a pain in the ass. I have suffered this in the past.
* You would need to provide title, description and image for the short URLs which preview you want to customize. The first two a relatively straightforward, but the image needs to be publicly available, which means you either take care of hosting it somewhere, or Shlink needs to provide image storing capabilities, which is a bit out of its scope.
  Also, once this is implemented, people will start asking for other OG attributes to be supported.
* The short URL both social networks and users are visiting is the same, but for users you return a redirect and for social networks shlink has to return a page including the OG tags.
  This is extremely error prone, and any implementation would be very fragile, having users that end up in the fake page, and social networks that are still redirected and therefore, they show the real preview and not the custom one.
  This is mainly because you have to use the User-Agent to determine who's "visiting" the URL. Also, some social networks perform HEAD requests sometimes, which is not documented and I found out just by doing reverse engineering.

Because of this, I don't think it's very likely that this is implemented in the short term, but I'm going to leave it open for others to react or provide more context.

**Comment by thehateguest** [comment]
Hey hi thanks for your fast reply!

> * The OG standard is quite different for every social network, which is a pain in the ass. I have suffered this in the past.

yes I know, but we could start from the easy/more used ones (like facebook/linkedin/twitter)

> * You would need to provide title, description and image for the short URLs which preview you want to customize. The first two are relatively straightforward, but the image needs to be publicly available, which means you either take care of hosting it somewhere, or Shlink needs to provide image storing capabilities, which is a bit out of its scope.

of course the image would be self hosted 

>   Also, once this is implemented, people will start asking for other OG attributes to be supported.

as far as I can tell looking at other services people usually just change the image (maybe as you said title and description but it’s not a priority for a lot of users)

> * The short URL both social networks and users are visiting is the same, but for users you return a redirect and for social networks shlink has to return a page including the OG tags.
>   This is extremely error prone, and any implementation would be very fragile, having users that end up in the fake page, and social networks that are still redirected and therefore, they show the real preview and not the custom one.
>   This is mainly because you have to use the User-Agent to determine who's "visiting" the URL. Also, some social networks perform HEAD requests sometimes, which is not documented and I found out just by doing reverse engineering.

I get what you are saying, I don’t think that could be a problem (having the two pages still up at the same time) - what I am trying to achieve is being able to post the same link on several different posts with a different preview image so that I can control which image is shown just on that post. I know this sounds like an unique problem but it’s something that is causing an headache to a LOT of social media managers right now :)
