### ISSUE TITLE
Support multi-segment custom slugs (slugs with slashes)

### ISSUE THREAD

**Issue by ThomasOrlita** [shlinkio/shlink#854]
Currently it's not possible to easily use `/` in URL slugs.
I tried adding `/` into `CUSTOM_SLUGS_REGEXP`, it works, but only partially.

The problem is that slashes get mixed up with the rest of the URL when using the REST API:
`"Cannot DELETE http://example.com/v2/short-urls/a/b!"`
URL-encoding doesn't seem to help here.

---

- [x] Support on short URL creation: Multi-segment slugs should be considered valid.
  - [x] If a feature flag is provided, allow multi-segment only if the feature is enabled.
- [x] Support on URL redirects: `https://doma.in/my/multi-segment/slug` should redirect properly
- [x] Support on REST endpoints where the shortcode/slug is part of the URL: Potentially, enforce URL encoding for this to work.
- [x] Handle conflict when `REDIRECT_APPEND_EXTRA_PATH` is `true` and multi-segment slugs are used.
- [x] Document Architecture Decission Record
- [x] Feature flag
  - [x] [Add new option to installer](https://github.com/shlinkio/shlink-installer/issues/166)
- [ ] https://github.com/shlinkio/shlink-web-client/issues/694
- [x] https://github.com/shlinkio/shlink.io/issues/312

**Comment by acelaya** [comment]
I think it should be possible to do this by tweaking a bit the router's paths definitions. I'll take a look.

**Comment by tobiasfichter** [comment]
Hey @acelaya,
can you estimate when you'll tackle this?

**Comment by acelaya** [comment]
I'm afraid I can't provide an estimation.

I work on this project on my free time, so I can't know beforehand when is that going to be.

It's also not prioritized at the moment for any upcoming version, si I would say it will be a couple of months probably.

That said, I'm open for sponsorship and I'm willing to prioritize requests from sponsors https://github.com/sponsors/acelaya

**Comment by saikarthikp9** [comment]
where can i set CUSTOM_SLUGS_REGEXP?

**Comment by chez14** [comment]
Hi @acelaya,

Since you asked for sponsorship, I'm adding my little contribution :' Is it still possible to prioritize this issue?

Thank you so much, I'm a big fan of your work!

**Comment by acelaya** [comment]
I have been working on this, and there are a couple of aspects to take into consideration in order to support it. I wanted to share it here for transparency.

## Short URL creation

On the one hand, `/` should be a valid character when providing a custom slug during short URL creation.

This part is currently easier than it was when this issue was created. Shlink 3.0.0 removed the `CUSTOM_SLUGS_REGEXP` completely, and now supports any character except for ` ` and `/`, which get replaced by `-`.

Removing `/` from that restriction should be easy.

## Route matching

The next big challenge is how routes are matched in Shlink (route matching allows the proper logic to be dynamically run depending on the requested URL).

Currently, the internal router matches individual path segments as route params, which has been good enough for single-segment slugs/short codes, but for multi-segment slugs, this presents some issues.

There are two types of affected routes:

### Non-REST routes

* `GET /{shortCode}`: The usual short URL you want to share with end-users. [See spec](https://api-spec.shlink.io/#/URL%20Shortener/shortUrl).
* `GET /{shortCode}/qr-code`: The URL that returns a binary image with a QR code pointing to a short URL. [See spec](https://api-spec.shlink.io/#/URL%20Shortener/shortUrlQrCode).
* `GET /{shortCode}/track`: A URL that can be used to track emails. [See spec](https://api-spec.shlink.io/#/URL%20Shortener/trackShortUrl).

For these, there are two possible options:

* Tweak the router so that it matches the whole multi-segment path as the `shortCode` param.
* Let the internal router throw a 404, and capture it in order to run the fallback logic.

The first option seems the easiest, but it actually has a lot of side effects and will become super hard to handle. Basically, by doing so, a route like `/{shortUrl}` can be matched by virtually anything, making other routes never match.

The second option is something I already used as part of https://github.com/shlinkio/shlink/issues/1080, and it worked quite nicely, so I will probably use this approach.

> Multi-segment slugs will also conflict with `REDIRECT_APPEND_EXTRA_PATH=true`. More on this later.

### REST routes

* `GET /rest/v2/short-urls/{shortCode}`: Get info about one specific short URL. [See spec](https://api-spec.shlink.io/#/Short%20URLs/getShortUrl).
* `DELETE /rest/v2/short-urls/{shortCode}`: Delete one specific short URL. [See spec](https://api-spec.shlink.io/#/Short%20URLs/deleteShortUrl).
* `PATCH /rest/v2/short-urls/{shortCode}`: Edit some attributes of a short URL. [See spec](https://api-spec.shlink.io/#/Short%20URLs/editShortUrl).
* `GET /rest/v2/short-urls/{shortCode}/visits`: Get visits on a specific short URL. [See spec](https://api-spec.shlink.io/#/Visits/getShortUrlVisits).

For these, the same two options are possible.

I'm currently experimenting on this, as the approach taken for the previous routes is not as easy to apply here, but I'm doing my best to get something working.

## Conflict with REDIRECT_APPEND_EXTRA_PATH

Shlink 2.8 introduced a feature which allows to redirect to a long URL as soon as provided short URL starts with a valid slug/short code, and then appending the rest of the short URL path to the long URL.

> For example, if you have a short URL `https://doma.in/foo` pointing to `https://example.com/very-long/url`, by visiting `https://doma.in/foo/bar/baz`, Shlink will match the beginning, and append the rest of the path (`/bar/baz` in this case) to the long URL before redirecting, resulting in `https://example.com/very-long/url/bar/baz`.

This would conflict with multi-segment custom slugs, but it's relatively easy to work around it.

No matter how multi-segment slugs are handled, we first try to match the whole URL to a custom slug, and if there's no match and `REDIRECT_APPEND_EXTRA_PATH` is `true`, then we try to match segments of the URL, starting with the first, then the two firsts, then the three firsts, and so on, until there's a match or provided URL segments are exhausted.

If there's a match, Shlink will append the "remaining" segments to the long URL before redirecting.

## Backwards compatibility

The final challenge is backwards compatibility.

Enabling this feature by default will make Shlink potentially behave differently in some cases, and I'm sure there are edge cases I didn't think about.

Because of that I would like to be able to disable this by default, and make people interested on it to explicitly opt-in via configuration or env var.

However, as explained in previous points, this feature affects several touchpoints, which will make enabling/disabling it via feature flag a bit trickier.

I still need to give this a deeper thought.

**Comment by acelaya** [comment]
So, after a lot of experimientation, I have managed to make it work by tweaking the router, which was initially not the option I wanted to follow.

The other option turned out to be harder than I thought, because if I let the router fail, then I still need some way to determine which specific route is potentially the matching one based on visited path, and for that, I need some kind of router anyway 😅.

However, this approach has one side effect:

Shlink is capable of tracking orphan visits (meaning, any visit to a URL that the router cannot match or an invalid short URL). Currently, Shlink also tracks the type of orphan visits, and this information is exposed via the API to be able to generate reports.

Currently supported types are:

* BASE_PATH: The base URL was visited, usually the bare short domain.
* REGULAR_NOT_FOUND: Any URL the internal router was not able to match.
* INVALID_SHORT_URL: The router matched the "short URL route", but then provided slug/short code does not resolve any existing short URL.

With the changes to support multi-segment slugs, any URL will always match the "short url route", which means there will be no orphan visits with REGULAR_NOT_FOUND type anymore.

This is not s super big deal, but I would treat it as a breaking change, so I will have to disable multi-segment slugs by default, and provide an env var or configuration to enable it actively under your own risk.

The changes have also two other "smaller" side effects:

* Shlink-web-client also uses the slug in some routes. I have tested that it does not work with multi-segment slugs, so it will need some changes in a future release to add support for this.
* Shlink has some extra routes used during development, that have stopped working with the router changes, and I will have to spend some time fixing them.

The benefit of this approach is that it actually requires way less changes in Shlink.

The main problem is that the order of registered routes matters, which could lead to malfunctions in the future if routes change or new routes need to be created.

**Comment by acelaya** [comment]
This feature is now implemented and will be part of Shlink v3.2.0, which is about to be released.

In order to enable it, you need to pass the env var `MULTI_SEGMENT_SLUGS_ENABLED=true`. If you are using the installer tool, you will be asked if you want to enable it.

Shlink-web-client does not support multi-segment slugs yet. It will be tackled as a bug, as part of v3.7.1, and released soon.

The rest of the considerations can be found in [the docs](https://shlink.io/documentation/some-features/#multi-segment-custom-slugs).

**Comment by acelaya** [comment]
I have just released shlink-web-client 3.7.2, which fully supports multi-segment slugs. It is already deployed in https://app.shlink.io
