### ISSUE TITLE
Base URL redirects always use 302?

### ISSUE THREAD

**Issue by codaamok** [shlinkio/shlink#867]
Maybe I'm seeing things, but am I correct in observing that the redirect options you configure when invoking `./install` are always 302, even if the user configures their short codes to be issued with 301? I have multiple domains responding on my shlink instance and I had to implement nginx rules to return 301 instead of 302 if someone queried `$http_host = mydomain.com` and `$request_uri = /`.

When a user advises Google of a "Change of address" via the Google Search Console, Google is expecting 301 and will not let the user submit the "Change of address" if it is anything else.

**Comment by acelaya** [comment]
This shouldn't probably be the case. If you have configured custom redirects for "not found" URLs, they should honor the type of redirects you configured, probably.

I'll take a look to see if there's any other consideration, but this looks like a bug to me.

**Comment by acelaya** [comment]
Hey @codaamok, I have fixed this behavior, so that redirects configured for the base path, not found short URLs and other not-found paths also respect the same status code configured during installation.

I even considered hardcoding higher caching times for these three, but I finally used the same logic as for regular short URLs, because it's planned to make shlink track these visits too, at some point.

The fix will be released later today/tomorrow with v2.4.1

**Comment by acelaya** [comment]
The v2.4.1 has just been released, including the fix for this.

**Comment by codaamok** [comment]
That's awesome, thank you so much @acelaya
