### ISSUE TITLE
Detect visits from bots

### ISSUE THREAD

**Issue by noook** [shlinkio/shlink#900]
#### Summary

When creating urls with visit count limited use, at least 2 visits are counted for each preview a social media is trying to display.

I know this is an edge case, but say I want my link to be seen only once on Messenger, I have to consider the recipient and I will trigger a preview request, and also that the recipient might open the link later when reloading the app and thus, making another preview request, consuming the last visit count available.

I have no idea how to implement this yet, but maybe providing a user agent blacklist / ip list would be enough ? Or not precise enough probably / easily imitable

**Comment by acelaya** [comment]
Being honest, it's not really that edge case.

Even if you don't set a limit of visits, sharing the link in social networks can affect the visits stats.

So yeah, it's something I would like to have.

The problem, as you guessed, is that there's no strong way to do this reliably.

Probably having a list of user agents would be the best approach, but social network crawlers can change those at any moment, so it's a bit fragile.

Another option would be to do it the other way around, and tracking only visits coming from known browser user agents, but it can also throw some false positives.

Then, even if there was a good way to do this, it would be something changing how shlink behaves, and therefore, a breaking change. Because of this, it should be opt-in and configurable.

And of course, this opens the door to people that will want it to behave differently depending on the link, to still track visits from bots but not count them for the limit, and many other combinations. It would require some time to determine how complex should the behavior be to cover as many use cases as possible, without making it a nightmare to maintain.

Si that's more or less the story behind it 😅

**Comment by noook** [comment]
That makes perfect sense, and I get it. I thought maybe there were other information we weren't aware of that could make this possible. Thanks for the enlightenment !

**Comment by acelaya** [comment]
I have updated the title of the ticket. I will start by checking of it's possible to detect three visits coming from bots, and once I have that, I'll implement more options based on that, on later iterations.

The options could include but not be limited to:

* Allow not counting those visits for the limit on a per link basis.
* Allow filtering those visits out when getting visits stats for a link or tag.

**Comment by garethjax** [comment]
Check if these docs may help:

- https://developers.facebook.com/docs/sharing/webmasters/crawler/
- https://github.com/monperrus/crawler-user-agents

Maybe it woud be necessary to build a "whitelist" or "blacklist" feature that the server owner may manage? 

Doing something definitive would be **very** hard, according to "whatismybrowser" the list of 50 MILLIONS user agents, is about 10 Gigabytes!

https://developers.whatismybrowser.com/useragents/database/

**Comment by acelaya** [comment]
Thanks for the links @garethjax, I will take a look at them :)

**Comment by MartinHotmann** [comment]
> Probably having a list of user agents would be the best approach

I dont think so, as the user-agent is very easy fakeable and you would really need to have all these GBs of Data which User-Agents all exist.
I would not go with something like explained here:

https://www.onely.com/blog/detect-verify-crawlers/

Get the IP and do a reverse Lookup and see where it belongs to. With this you can easily and very precisely tell if the request came from one of the most common Bots/Crawler/Inspectors.

As this request is specially about "socialmedia-bots": they would be very easy to identify with this method.


Example:

you post a ShortLink in Instagram and therefor Instagram checks (calls) the posted link.
Now we check the IP and if there is a PTR and if there is it is very easy to identify if it was a bot and where the bot belongs to

**Comment by acelaya** [comment]
Thanks @MartinHotmann.

Now you can remove the word "easy" from everything you said, and then it could be closer to reality 😂

**Comment by acelaya** [comment]
Hey @MartinHotmann. Now that I'm reading my message again I realized it could be misinterpreted, so just to clarify, I was just trying to make a bad joke 😅

**Comment by MartinHotmann** [comment]
> Hey @MartinHotmann. Now that I'm reading my message again I realized it could be misinterpreted, so just to clarify, I was just trying to make a bad joke 😅

Yeah totally forgot that the standardtemplate for us germans does not come with the attribute "humor" 😅
Thats why I miss all the jokes :P

**Comment by acelaya** [comment]
I have decided that, to begin with, I will use this library https://github.com/JayBizzle/Crawler-Detect, to just determine (reasonably) if the visit comoes from a bot/crawler, and save that in the visit as a flag.

I will also enhance the visits endpoints to allow exlcuding visits from potential bots.

In future versions I will try to apply more advanced logics on top of that.
