### ISSUE TITLE
QR codes for different domains and question re size in path

### ISSUE THREAD

**Issue by codaamok** [shlinkio/shlink#905]
#### Summary

I love Shlink, it's simple and very nice to use.

I have a couple of questions:

1. Is it possible to add a `domain` parameter for the QR code endpoint? I think with the way it currently is, we can only generate QR codes for short codes associated with the default domain of the Shlink instance.

1. I was surprised to see that to specify the size for a QR code, `size` is passed as part of the path in the URI and not as a parameter. I would have expected it to be a parameter, e.g. like `format`. I appreciate the `format` parameter was added after the endpoint was created, so maybe that's part of the reason why.

Maybe you'll be interested to know that I'm currently working on a PowerShell module for Shlink: [PSShlink](https://github.com/codaamok/PSShlink)

**Comment by acelaya** [comment]
First of all, thanks for the kind wirds :slightly_smiling_face: 

> Is it possible to add a domain parameter for the QR code endpoint? I think with the way it currently is, we can only generate QR codes for short codes associated with the default domain of the Shlink instance.

The domain is inferred from the URL itself. So if you have created a short URL with short-code `abc123` and want to generate the QR code for domain foobar.com, you should call foobar.com/abc123/qr.

If it's not working like that, it could be a bug. Let me know in that case.

> I was surprised to see that to specify the size for a QR code, size is passed as part of the path in the URI and not as a parameter. I would have expected it to be a parameter, e.g. like format. I appreciate the format parameter was added after the endpoint was created, so maybe that's part of the reason why.

You are right. The size is part of the path and not the query because it was added since the very beginning, but it was probably a bad decission, as it's not very usable to allow adding more optional params to the path.

I may consider changing that for Shlink v3.0.
