### ISSUE TITLE
Webhook not being triggered upon shorturl visit if GEOLITE_LICENSE_KEY is not set

### ISSUE THREAD

**Issue by markkuit** [shlinkio/shlink#937]
#### How Shlink is set-up

* Shlink Version: 2.4.0
* PHP Version: 7.4.11
* How do you serve Shlink: Docker image
* Database engine used: MariaDB (10.5.8)

#### Summary

The `VISITS_WEBHOOKS` environment variable has been set (verifiable by looking at `set`), but webhooks are not being called upon visiting a generated shorturl. This seems to be happening regardless of network restrictions (none there anyway), proven by trying setting `http://localhost` as webhook and listening on port 80 in the Shlink container itself, in vain.
For the sake of testing I also tried running a docker-compose stack with nothing but the Shlink service and the localhost webhook, still in vain.

#### Current behavior

On a fresh stack, upon generation of a new shorturl, visiting it does not trigger a call to the specified webhook.

#### Expected behavior

Webhook should have been contacted upon shorturl visit.

#### How to reproduce

I'm attaching the `docker-compose.yml` in use, with sensitive content replaced.

[docker-compose.yml.txt](https://github.com/shlinkio/shlink/files/5730347/docker-compose.yml.txt)

**Comment by markkuit** [comment]
Upon further information, it'd look like this doesn't happen if a MaxMind license key is provided via `GEOLITE_LICENSE_KEY`. This might mean the process gets stuck trying to download the database or geolocating the IP address, thus never reaching the webhook step.

I'll update the issue title accordingly.

**Comment by acelaya** [comment]
The problem here is that the default license key is being used by too many people. It reaches the daily download limit every day, and once that happens, if your instance tries to download a new version, it times out. That in turn causes the tasks that should be triggered as a result of locating a visit, to never be triggered.

Shlink tries to download for 15 seconds, and then times out and falls back to the old GeoLite db file. However, if you don't have an old file (because you are trying to download for the first time), then it can't locate the visit and the tasks do not get triggered.

Setting your own license key is currently considered mandatory, even though Shlink kind-off works without it for historical reasons.

Once Shlink 3 is released, it will enforce the key to be set, and the default license key will be disabled.

I will document this though, so that people don't waste too much time, as this is a very unintuitive issue.
