### ISSUE TITLE
REST API not following main site configuration

### ISSUE THREAD

**Issue by jitdor** [shlinkio/shlink#940]
I have built a Telegram bot that uses the Shlink REST API to create short URL. My Shlink instance has a shortcode length setting of 4 characters (specified during bin/install). However, URLs generated via the REST API seem to be always 5-character in length instead. Is there a hidden fucntion within the REST API which can configure the code length?

Similarly, is there a way to disable URL validation and allow re-using of existing URL for requests sent to the REST API?

Thank you!

**Comment by acelaya** [comment]
The three things can be customized on a per-URL basis. Take a look at the docs for more details: https://api-spec.shlink.io/?version=v2.4.2#/Short%20URLs/createShortUrl

> However, URLs generated via the REST API seem to be always 5-character in length

If you make sure you don't send `shortCodeLength` at all while creating the short URL, it should use the global config, which is set to 4. If that's not the case, we could be facing a bug.

> is there a way to disable URL validation

Yes. You need to send `validateUrl: false`.

Just take into consideration this was added on Shlink v2.4

> allow re-using of existing

This is also possible, by sending `findIfExists: true`.

When you send that, Shlink will return existing short URLs if the params you sent match an existing one, instead of creating a new one.

The link I shared above explains all the checks done internally when this flag is sent.

**Comment by jitdor** [comment]
Thanks @acelaya! Upon closer inspection of the API, I realized the parameters supported by the POST and GET methods are different. As I'm currently using the GET method at `.../short-urls/shorten`, it seems I'll have to adapt my code to use the POST method instead.

Thanks again for pointing it out!

**Comment by acelaya** [comment]
Perfect. I'll close this issue then. Feel free to open a new one if you face any other issue.
