### ISSUE TITLE
Exclude specific domain names from valudateUrl

### ISSUE THREAD

**Issue by jitdor** [shlinkio/shlink#949]
By default, shlink would attempt to validate a given URL and would only shorten it if the validation passes, unless the `validateUrl: false` flag is set.

However, certain websites, such as www.bilibili.com, would always fail the shlink validation. (Sample URL from a shared video link https://www.bilibili.com/video/BV1hV411h7QQ)

While it is possible to add this logic within the client application, I am wondering if shlink would consider adding a feature to skip validation as long as the given URL is from a user-input list of domains?

Thank you!

**Comment by acelaya** [comment]
Hey @jitdor 

I'm not really sure about this. At the moment there are two ways to make URLs to be validated or not.

* Via global config/env vars, which either makes all short URLs to be validated or none.
* Via `validateUrl` param, which allows to override the former on a per URL basis.

Adding a third option to achieve the same would make the whole process too complex, with too many combinations.

I think the two options that currently exist make it flexible enough, without introducing too much maintainability debt.

* If there's one URL that you know is going to always fail validation (because it's reachable only from some private network or anything), just send `validateUrl: false`. That's the param's purpose.
* If you know that, in most of the cases you are going to end up shortening non-reachable URLs, set the global config to `false`.
