### ISSUE TITLE
Failed install did not resume with existing settings

### ISSUE THREAD

**Issue by Roy-Orbison** [shlinkio/shlink#996]
#### How Shlink is set-up

* Shlink Version: 2.5.2
* PHP Version: 7.4
* How do you serve Shlink: n.a.
* Database engine used: MariaDB

#### Summary

When installing from PHP CLI , after seeing this message in the interactive responses:
> Custom configuration properly generated!

...an error occurred:
> [ERROR] Error generating database..

It was my fault because I pasted in extra characters in the Unix socket setting, though the config file had been successfully created. I ran the installation again but it did not read my previous answers to the interactive settings to use them as defaults.

#### Current behavior

Install ignores existing config file.

#### Expected behavior

Load config file if present and allow the previous settings to be used as default or otherwise chosen.

#### How to reproduce

Provide an invalid db config parameter at install.

#### Workaround

After manually correcting the socket path in `config/params/generated_config.php`, I had a quick look at the installer after grepping for the last success message, then temporarily patched it to read the existing file (though this didn't allow me to answer any of the questions again):

```patch
--- a/vendor/shlinkio/shlink-installer/src/Command/AbstractInstallCommand.php     2021-02-01 13:12:49.288617861 +1100
+++ b/vendor/shlinkio/shlink-installer/src/Command/AbstractInstallCommand.php     2021-02-01 13:12:16.120444562 +1100
@@ -81,9 +81,9 @@

     private function resolvePreviousConfig(SymfonyStyle $io): ImportedConfig
     {
-        if ($this->isUpdate()) {
+        #if ($this->isUpdate()) {
             return $this->assetsHandler->resolvePreviousConfig($io);
-        }
+        #}

         return ImportedConfig::notImported();
     }
```

The install then progressed like so:
>Welcome to Shlink!!  
> This tool will guide you through the installation process.
>
> Do you want to import configuration from previous installation? (You will still be asked for any new config option that did not exist in previous shlink versions) (yes/no) [yes]:
> \>
>
> Previous shlink installation path from which to import config:
> \> .
>
> Custom configuration properly generated!
>
>Initializing database... Success!
>Updating database... Success!
>Generating proxies... Success!
>
>
> [OK] Installation complete!

**Comment by acelaya** [comment]
This is the expected behavior. The options are:

* `bin/install`: It asumes you are installing shlink for the first time and asks all the questions.
* `bin/update`: It allows you to import the config from a previous version, in which case it will skip asking the questions for which it finds a value from imported config. This websites only new options introduced in the new version are asked.
* `bin/set-option`: It can be used to change the value for individual options.

What happened to you is kind of an edge case. The options to solve it are, running the install again and providing all the config options, or running the set-option one to change the socket and then run the database creation (`bin/cli db:create`) and database migration (`bin/cli db:migrate`) commands, however these two are not documented.

If you want, you can open a feature request here https://github.com/shlinkio/shlink-installer/issues, to make the install command set the default value for all questions based on the existing config file, if any, but it's going to be low priority as the benefit is not that high.

**Comment by Roy-Orbison** [comment]
The installer completely crashing on being unable to connect to the database doesn't seem like an edge case to me, it's common enough to mistype connection credentials. It seems like plain data loss to me, e.g. writes data like the MaxMind licence to key to disk, then overwrites it on next install attempt.

I did see `db:create` in the help after I'd installed shlink and ran `bin/cli` without any options.

**Comment by acelaya** [comment]
It's an edge case in the sense that you can re-run the installer and provide the options again. There's no hard-stopper where you lost everything.

Running the command again will take you less than one minute and it won't bother you ever again.

I know it's cumbersome to have to introduce everything again, but the workaround is so simple that it's not worth the effort.
